### ISSUE TITLE
Updating translation doesn't bust the cache_key

### ISSUE THREAD

**Issue by pwim** [shioyama/mobility#101]
When you update a translation (table backend), the cache key is not being invalidated. 

There's two approaches I see of fixing this:

#### Add `touch: true` when setting up the `belongs_to` relationship. 

The advantage of this approach is it is quite simple to implement, and makes the model behave like any of the backends that store the translation within the model.

The disadvantage of this approach is that if someone is using the `updated_at` for something more than cache invalidation, this might not match their expectation. 

Globalize has `touch` as an option. I've made [a branch of mobility using this approach](https://github.com/pwim/mobility/tree/table-touch), which I'll use for now on my app.

#### Overwrite the cache_key

This is the approach [that globalize takes](https://github.com/globalize/globalize/blob/ef1e362f3144b2276d89f47407c67ffa3fc1f9f2/lib/globalize/active_record/instance_methods.rb#L164-L166). 

One possible issue I see with their implementation is that it constructs the `cache_key` using only the translation based on the current locale. If you're only using methods like `event.title`, this works fine. But if you access a translation in a different locale than the one you're in (e.g., when the locale is `:en`, accessing `event.title(:ja)`), the cache_key will be incorrect.

More generally, I see this approach as potentially having performance implications, as now you need to load the translations to calculate the cache_key.

**Comment by shioyama** [comment]
I'm actually aware of this one since I saw it in Globalize, and I was planning to add a very simple `touch` option to the table backend for it, but waiting for someone to actually ask for it :smile:

There were some issues in Globalize as I remember where one person wanted one thing, and another wanted another, and each conflicted with each other (I believe that's why `touch` became an option rather than preset by default). So need to think a bit about this, and performance would be one thing to consider for sure.

Any opinions on this would help, but adding  a `touch` option as a first step would be very simple, and leaving it off by default wouldn't affect current users who wouldn't want it.

**Comment by shioyama** [comment]
Actually if you modify your branch to make `touch` an option which is off by default, and make it a PR, I'll merge it right away.

**Comment by pwim** [comment]
While I could make this an option, and it would certainly solve my case, I'd like to see if there's some solution that can prevent people getting into the same situation as me, where our users reported the broken caching (in our case, it seems a bit more subtle - for whatever reason caching was working under Rails 5.0 with mobility, but upgrading to 5.1 broke it).

I've taken a look at globalize's history with touch. As far as I could tell, globalize was using the `touch` option in the past, but disabled it to work around a Rails bug. Eventually that Rails bug was resolved, and so someone added touch support again, this time as an option. So from my reading of it, there wasn't ever anyone who explicitly wanted to be able to disable touching.

You're right, some people might theoretically want mobility to not touch the records. But I see that as the exceptional situation. Rather than making it an option, which people might not even use, I'd rather change it to always touch, and only add support for not touching if this is explicitly requested. You're right that we'll be changing the behavior, but that's what the changelog is for.

**Comment by shioyama** [comment]
Alright, you make a convincing case. Can you make a PR from your branch then? I just need some time to read up on the history in Globalize to refresh my memory, but I think you're right that on balance, `touch: true` as a default would be better than the current situation.

**Comment by sumeetattree** [comment]
Is there any way I can disable this in the development environment? I spent a few minutes trying to debug why the translations weren't updated before it hit me it might be caching results.

**Comment by pwim** [comment]
@sumeetattree I don't think my original report is related to the problem you're experiencing, so please create a new issue. Also, including specific examples, such as code to reproduce your problem, would help a lot with understanding your problem.

**Comment by sumeetattree** [comment]
@pwim Please ignore me. I had a different problem. My filter ordering for setting the locale was off. I was setting the locale before I had the current_user available in my code.
