### ISSUE TITLE
SimpleForm displays single line input fields for translated attributes

### ISSUE THREAD

**Issue by jmuheim** [shioyama/mobility#109]
I have a text field `:content`.

Usually, SimpleForm correctly displays a textarea for it:

    = f.input :content

When translating the field using Mobility, it displays a single line input!

If you need a demo Rails application, I can set up one for you.

**Comment by pwim** [comment]
@jmuheim To work around this, use SimpleForm's `as` argument

``` ruby
= f.input :content, as: :text
```

**Comment by shioyama** [comment]
Thanks @pwim, I was going to look to see if something like that was possible.

@jmuheim Mobility can't really fix this kind of problem, since ultimately translated attributes are virtual attributes, not table columns. There are only going to be situation-specific solutions like the one above.

However, I will add the workaround above to the wiki.

**Comment by shioyama** [comment]
Added to the [wiki page on using Mobiliity with forms](https://github.com/shioyama/mobility/wiki/Using-Mobility-with-Forms).

**Comment by pwim** [comment]
@shioyama SimpleForm uses [type_for_attribute](http://api.rubyonrails.org/classes/ActiveRecord/ModelSchema/ClassMethods.html#method-i-type_for_attribute) to determine which input type to create. I suppose we could overwrite this method to delegate to the backend, but that might open another can of worms. I don't see this as something Globalize needs to support, but if someone was to want to step up and create a PR to handle it, I think it would be worth considering.

**Comment by shioyama** [comment]
~Globalize~ Mobility :wink:

**Comment by pwim** [comment]
Good catch. For the record, this isn't something that Globalize handles either.

**Comment by shioyama** [comment]
> I suppose we could overwrite this method to delegate to the backend, but that might open another can of worms.

That's an idea, but I'd suggest maybe having another gem like `mobility-simple_form` or something with a plugin to do this would be best. But if the solution in this case is as simple as `as: :text`, I'm not sure it's really worth the effort.
