### ISSUE TITLE
All translations in on form?

### ISSUE THREAD

**Issue by mcmegavolt** [shioyama/mobility#145]
Hi there! How to build a form with all translations, like:

- name [en]: _______
- name [fr]: ________
- name [de]: _______
- ...

Thanks!

**Comment by shioyama** [comment]
Thanks for your question. Can you ask on stackoverflow with the [mobility](https://stackoverflow.com/questions/tagged/mobility) tag? I'd rather not have the github issues become a forum for usage questions.
