### ISSUE TITLE
Interpolations?

### ISSUE THREAD

**Issue by glebm** [shioyama/mobility#162]
For example, consider a model with a translated `greeting` attribute with value such as `Hello, %{name}!`.

with Globalize, the following works:

```ruby
record.greeting(name: 'Chris')
```

with Mobility, interpolation is not performed.

I've tried migrating from globalize as per [the wiki article](https://github.com/shioyama/mobility/wiki/Migrating-from-Globalize).

**Comment by shioyama** [comment]
Updated the wiki to mention this is not currently supported.

**Comment by shioyama** [comment]
I suppose something like:

```ruby
record.greeting(interpolate: { name: 'Chris' })
```

would work.

**Comment by glebm** [comment]
This API makes sense. I would prefer `interpolations` as the key though.

**Comment by pwim** [comment]
I don't see a need for this to be part of mobility, as [String already supports interpolation via the % method](https://ruby-doc.org/core-2.5.0/String.html#method-i-25):

``` ruby
"Hello, %{name}!" % { name: "Chris"} # => "Hello, Chris!"
```

So you should be able to use it to get the desired result: 

``` ruby
record.greeting % {name: 'Chris'} # => "Hello, Chris!"
```

As an alternative, looking at globalize's implementation, it just seems to be doing some argument checking and then calling `I18n.interpolate`. So I think the following should be equivalent to globalize:

``` ruby
I18n.interpolate(record.greeting, name: 'Chris') # => "Hello, Chris!"
```

I didn't look into the details of what the difference between `%` and `I18n.interpolate` is under the hood.

**Comment by glebm** [comment]
@pwim I18n interpolation is not as naive as this and should use the I18n backend settings.

**Comment by shioyama** [comment]
[Here](https://github.com/svenfuchs/i18n/blob/7c6ccf471ecf2c0a406d3a5317375f28d2da3613/lib/i18n/interpolate/ruby.rb#L20-L35) is the implementation in I18n.

**Comment by glebm** [comment]
@shioyama That's not all of it, another important part is:

https://github.com/svenfuchs/i18n/blob/7c6ccf471ecf2c0a406d3a5317375f28d2da3613/lib/i18n/backend/interpolation_compiler.rb

**Comment by glebm** [comment]
Manually calling `I18n.interpolate` should work, even if a bit awkard.

**Comment by shioyama** [comment]
It's true that the difference between:

```ruby
I18n.interpolate(record.greeting, name: 'Chris')
```

and

```ruby
record.greeting(interpolate: { name: 'Chris' })
```

is pretty small, if that's all the plugin would do. It's also more obvious what is going on in the first case.

**Comment by shioyama** [comment]
I'm going to close this, it doesn't seem like a killer feature. If anybody things otherwise, please feel free to comment.

**Comment by IngoTomahogh** [comment]
I just want to remark that I found it useful in one project to monkey patch `String`, adding an `interpolate` method that calls `I18n.interpolate` under the hood, and adds some functionality like (per default) replacing missing interpolations with error messages in the interpolated string and writing log messages about them.

With that patch, the above can be achieved with a call like this (± side effects like logging):
```ruby
record.greeting.interpolate(data: { name: 'Chris' })
```

Having interpolation as a built-in feature would have been wasted here, and think the interface is not much clumsier than that of globalize, and more obvious.
