### ISSUE TITLE
Support order clause on translated queries

### ISSUE THREAD

**Issue by shioyama** [shioyama/mobility#171]
Mobility does not currently support an `order` clause on translated queries. We should see how much work it would be to support it in both ActiveRecord and Sequel.

## Context

You can currently query on a translated attribute with the `i18n` scope, like this:

```ruby
Post.i18n.where(title: "foo")
```

and Mobility will figure out what query is actually needed to fetch a post with  a title "foo" in the current locale.

However, ordering results is not supported:

```ruby
Post.i18n.where(title: "foo").order(:title)
# raises: ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR: column posts.title does not exist
```

This should be possible to implement without too much work.

Ref: #169

**Comment by eiapopeia** [comment]
My current _"workaround"_ for table backend is:
``` ruby
Post.i18n.where(title: 'foo').order('post_translations.title')
```

**Comment by eiapopeia** [comment]
Workaround **since upgrade to 0.7.5**
``` ruby
Post.i18n.where(title: 'foo').order('post_translations_de.title')
```

**Comment by shioyama** [comment]
Thanks! I'll update the [section of the migrating page on querying](https://github.com/shioyama/mobility/wiki/Migrating-from-Globalize#querying).

**Comment by shioyama** [comment]
In general it would be:

```ruby
Post.i18n.where(title: 'foo').order("post_translations_#{Mobility.normalize_locale}.title")
```

**Comment by eiapopeia** [comment]
Another "workaround" for sorting all records (_that have a title_):
``` ruby
Post.i18n.
  where.not.(title: nil). #triggers mobility to fetch the translations table
  order("post_translations_#{Mobility.normalized_locale}.title")
```

**Comment by shioyama** [comment]
Yeah, it's kind of ugly that you need to add a query just to get around the limitations of Mobility.

Here's a way to do it without the `where(title: nil)` bit:

```ruby
backend = Post.mobility_backend_class(:title)
backend.apply_scope(Post.all, backend[:title, Mobility.locale], Mobility.locale).
  order("post_translations_#{Mobility.normalized_locale}.title")
```

`apply_scope` was added in 0.7, it's used internally by Mobility to do stuff like joining other tables.

**Comment by shioyama** [comment]
Actually that can be simplified just a bit:

```ruby
locale = Mobility.locale
node = Post.mobility_backend_class(:title)[:title, locale]
backend.apply_scope(Post.all, node, locale).order(node)
```

`node` here is `"post_translations_#{Mobility.normalized_locale}.title"` so you can use it to simplify things a bit, so you don't need to explicitly reference `post_translations`. Also, this will work for any backend now.

**Comment by shioyama** [comment]
Hi everyone who upvoted this issue, please give #261 a try and let me know if it works for you.

**Comment by shioyama** [comment]
To everyone following this thread: `order` is now supported in version 0.8.0. Please update your Gemfile and let me know if you notice any issues!
