### ISSUE TITLE
Question: [postgres backend] why should the column default to an empty string?

### ISSUE THREAD

**Issue by jgrau** [shioyama/mobility#178]
First of all thank you for a great gem. I have a question that I tried to find an answer to by reading the readme and the wiki and the old commits but I couldn't find it so I'm posting it here.

When using the postgresql `jsonb` backend the wiki is very clear to default to an empty string

> Once the migration is created, make sure to change the actual migration to set the default value of the column(s) to an empty string (''), so it looks like this

Is there a reason not to default to an empty json object `{}`?

**Comment by shioyama** [comment]
Thanks, that's actually a good question. I had problems at the time trying to set the default to an empty json object, although it would seem to make more sense than an empty string.

I can try using an empty json object and see what goes wrong, of if anything goes wrong. (So far this hasn't been an issue that anyone has raised, so I've just let it be.)

Just to check: did you have any issues with the blank string default, or did you just find that it would make more sense to use an empty object?

**Comment by jgrau** [comment]
Awesome. Thanks for your reply.

@rchand knows a bit more of the issue we had but AFAIK the problem was reading the values in environments with 'stronger type checking' than ruby.

**Comment by rchrand** [comment]
Yeah, i ran into problems trying to read the default value using the [Postgres driver for Ecto](https://github.com/elixir-ecto/postgrex) which we have used to turn jsonb into native maps before with success. 

Did a little testing with reverting the default value to `{}` and every entry along with it, and so far so good. Although our use of Mobility is limited at the moment. Thanks for a great gem.

**Comment by shioyama** [comment]
> Yeah, i ran into problems trying to read the default value using the Postgres driver for Ecto which we have used to turn jsonb into native maps before with success.

Wow interesting! Then yes for sure I can see why the default value would matter there.

I started a PR in #179 just changing the default in the specs schema to see what breaks, if anything breaks. I'll try to follow up, agree this should be changed if there are no blocking issues.

**Comment by shioyama** [comment]
Specs are passing for me locally with AR 5.2.0.beta, so this may be a simple matter of changing the wiki and specs to recommend/use the empty jsonb object :smile:

**Comment by rchrand** [comment]
Awesome, thanks for the answer and quick response 😄
