### ISSUE TITLE
uniqueness validator fails in Rails 5.2 rc2

### ISSUE THREAD

**Issue by kevin-jj** [shioyama/mobility#191]
## Entity
```ruby
class Taxon < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  
  extend Mobility
  translates :name, type: :string

  extend FriendlyId
  friendly_id :name, use: [:history,:mobility]
end
```
## Test
```ruby
t = Taxon.i18n.find_by(name: "Clothing")
t.name  "Clothing"
t.slug "clothing"

t1 = Taxon.create(name: "Clothing")
t1.name  Clothing""
t1.slug "clothing-6525635e-bdb8-492e-aaad-125ad75da630""
```

Isn't mobility compatible with Rails 5.2 rc2? @shioyama

**Comment by shioyama** [comment]
I've just released 0.5.1 which passes all specs (including uniqueness validator specs) with 5.2.0.rc2. Can you post an actual failing test which does not depend on FriendlyId? If not, then it's an issue with the FriendlyId/Mobility gem.

**Comment by shioyama** [comment]
Also, please specify which version of Mobility + FriendlyIdMobility you're using.

**Comment by kevin-jj** [comment]
* friendly_id-mobility (0.5.3)
* mobility (0.5.1)

**Comment by shioyama** [comment]
Ok, but please post a real test with no friendly id.

Here are the [current uniqueness validator specs](https://github.com/shioyama/mobility/blob/2cac7538636f5213e66850759896ed587f48250d/spec/support/shared_examples/validation_examples.rb). They aren't super detailed, but they test all standard cases.

**Comment by kevin-jj** [comment]
It passed all specs without friendly_id-mobility. Maybe it's an issue with friendly_id-mobility.

Do I need to copy this post to issues list in friendly_id-mobility gem?

**Comment by shioyama** [comment]
Are you sure it's not a problem with *FriendlyId*? See e.g. norman/friendly_id#856.

I'll run tests in FriendlyIdMobility against AR 5.2.0.rc2, but it's not high priority.

**Comment by shioyama** [comment]
See shioyama/friendly_id-mobility#5.

**Comment by kevin-jj** [comment]
I migrates from globalize to mobility today while uniqueness validator works well in Globalize, friendly_id-globalize gem.

**Comment by shioyama** [comment]
That's fine, but I don't go digging for bugs without failing specs. I'm running specs against Rails 5.2.0.rc2 in friendly id mobility, if they fail I'll try to fix them. Otherwise I won't do anything until there is a clear failing test to work from.

**Comment by kevin-jj** [comment]
I see. Thanks you for creating this valueable gem.

**Comment by shioyama** [comment]
Also, if you migrated from Globalize you might want to check the [migration guide](https://github.com/shioyama/mobility/wiki/Migrating-from-Globalize).

**Comment by kevin-jj** [comment]
Because I prefer to key_value as a backend to translate attributes, it's boring for me to see some xxx_translation table in globalize gem.

**Comment by shioyama** [comment]
Try moving the `validates :name, presence: true, uniqueness: true` to *after* you call `translates`:

```ruby
class Taxon < ApplicationRecord
  extend Mobility
  translates :name, type: :string

  extend FriendlyId
  friendly_id :name, use: [:history,:mobility]

  validates :name, presence: true, uniqueness: true
end
```

shioyama/friendly_id-mobility#5 is passing, so I don't see any other possible issue.

**Comment by shioyama** [comment]
Please confirm that fixes it. I should make a note somewhere that you need to call the validator after the mobility stuff, otherwise it won't work.

**Comment by shioyama** [comment]
Actually I originally added this validator in response to an issue posted by you (#20). I mentioned there that the validator had to be included *before* calling `validates`, so I'm pretty sure that is the problem you're seeing.

**Comment by kevin-jj** [comment]
It works out. Thanks @shioyama

**Comment by shioyama** [comment]
:+1:
