### ISSUE TITLE
Uniqueness validation does not work

### ISSUE THREAD

**Issue by kevin-jj** [shioyama/mobility#20]
```ruby
validates :name, presence: true, uniqueness: true
translates :name
```

xxxx.name does not exist

**Comment by shioyama** [comment]
Here's the PR on Globalize: https://github.com/globalize/globalize/pull/121

I don't want to do this type of hack within Mobility. Maybe create an external gem which you'd have to include, say `mobility-uniqueness` or something. Need to think about it.

I'm removing the "bug" label because I don't consider this a bug, but a feature request.

**Comment by kevin-jj** [comment]
Thanks for quick response.  

It seems that more compatible works need to do if friendly_id , globalize, mobility gem work together.

**Comment by shioyama** [comment]
So I checked this quickly. Presence validation works fine as expected. Uniqueness does not work. Depending on the backend, it will either not work as expected, or it will raise an error (complaining that a column does not exist).

> It seems that more compatible works need to do if friendly_id , globalize, mobility gem work together.

Are you using globalize and mobility together? That seems a bit strange.

About compatiblity, the only issue I see here is with *uniqueness* validation. Are there any other issues you are experiencing?

**Comment by kevin-jj** [comment]
>Are you using globalize and mobility together? That seems a bit strange.

>About compatiblity, the only issue I see here is with uniqueness validation. Are there any other issues >you are experiencing?

Yes.  I'd like to look into which gem is suitable to our application. It seems that mobility gem  does not work well with validating attribute and ancestry gem.

**Comment by shioyama** [comment]
I see. Well, the uniqueness problem can be solved, as a plugin or extension to Mobility.

For now, if you want a quick fix, you can add this class somewhere in your application:

```ruby
class MobilityUniquenessValidator < ::ActiveRecord::Validations::UniquenessValidator
  def validate_each(record, attribute, value)
    klass = record.class
    if klass.translated_attribute_names.include?(attribute.to_s)
      relation = klass.i18n.where(attribute => value)
      relation = relation.where.not(klass.primary_key => record.id) if record.persisted?
      relation = relation.merge(options[:conditions]) if options[:conditions]

      if relation.exists?
        error_options = options.except(:case_sensitive, :scope, :conditions)
        error_options[:value] = value

        record.errors.add(attribute, :taken, error_options)
      end
    else
      super
    end
  end
end
```

Now in your models, *before* you call `validates`, just add this line:

```ruby
class UniquenessValidator < ::MobilityUniquenessValidator; end
```

This is a very basic uniqueness validation. I should work with any backend other than the serialized backend, but without the `scope` option.

**Comment by shioyama** [comment]
Basic uniqueness validation, including scopes, should work now using `master` as long as you `include Mobility` before adding validations to your model.

**Comment by kevin-jj** [comment]
It works out.  Thanks @shioyama

**Comment by daniel-gato** [comment]
not working in rails 7

**Comment by shioyama** [comment]
Yes, that's what the specs test.

> We want the model to validate the presence of all locales (name_en, name_fr, etc)

There's nothing in Mobility to do this, so you'd have to implement it yourself.

**Comment by jussihirvi** [comment]
As a dirty fix, using Rails 6, I wrote my own uniqueness validator. Mobility query plugin must be active for i18n to work here. You can put the validator to helpers, concerns, or elsewhere. 

    class MyUniquenessValidator < ActiveModel::EachValidator
        def validate_each(record, attribute, value)
            passed = false
            count = record.class.i18n.where(attribute => value).count
            passed = true if record.persisted? && count <= 1
            passed = true if !record.persisted? && count == 0
            record.errors.add(attribute, ::I18n.t('activerecord.errors.message.unique'))  
        end
    end

Then call it from the model with for example like this: 

    validates :name, presence: true, my_uniqueness: true

**Comment by jussihirvi** [comment]
I solved this by writing a custom validator. The Mobility query plugin must be active for the i18n search to work. This is Rails 6 and Mobility 0.8.13. 

    class MyUniquenessValidator < ActiveModel::EachValidator

      def validate_each(record, attribute, value)
        passed = false
        count = record.class.i18n.where(attribute => value).count
        passed = true if record.persisted? && count <= 1
        passed = true if !record.persisted? && count == 0
        record.errors.add(attribute, ::I18n.t('activerecord.errors.message.unique')) unless passed
      end
    end
    
You can call this from the model for example like this: 

    validates :name, presence: true, my_uniqueness: true

**Comment by egemen-dev** [comment]
This works like a charm! Thanks @jussihirvi 

> I solved this by writing a custom validator. The Mobility query plugin must be active for the i18n search to work. This is Rails 6 and Mobility 0.8.13.
> 
> ```
> class MyUniquenessValidator < ActiveModel::EachValidator
> 
>   def validate_each(record, attribute, value)
>     passed = false
>     count = record.class.i18n.where(attribute => value).count
>     passed = true if record.persisted? && count <= 1
>     passed = true if !record.persisted? && count == 0
>     record.errors.add(attribute, ::I18n.t('activerecord.errors.message.unique')) unless passed
>   end
> end
> ```
> 
> You can call this from the model for example like this:
> 
> ```
> validates :name, presence: true, my_uniqueness: true
> ```

I had to change it a bit but that's ok. 

Turned it to something like because I'm using mobility 1.3.0 and rails 7

```rb
count = Mobility::Backends::ActiveRecord::KeyValue::StringTranslation
            .where(locale: locale)
            .where(translatable_type: self.class.to_s)
            .where(key: item, value: self.send(:"#{item}_#{locale}"))
            .count
```
