### ISSUE TITLE
Is querying documentation wrong?

### ISSUE THREAD

**Issue by samuelpismel** [shioyama/mobility#248]
When I try to do some LIKE queries following the documentation I got  this error:
```
[1] pry(main)> Video.i18n{ |title| title.matches("BCC") }
NoMethodError: undefined method `matches' for #<Mobility::Plugins::ActiveRecord::Query::VirtualRow:0x000056238d0637e8>
from /home/samuel/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/mobility-0.7.1/lib/mobility/plugins/active_record/query.rb:57:in `method_missing'
```
But when I do this, it works:
```
[2] pry(main)> Video.i18n{ |item| item.title.matches("BCC") }
  Video Load (8.7ms)  SELECT "videos".* FROM "videos" INNER JOIN "video_translations" "en_video_translations" ON "en_video_translations"."video_id" = "videos"."id" AND "en_video_translations"."locale" = 'en' WHERE ("en_video_translations"."title" ILIKE 'BCC')
=> []

```
I think it is an documentation issue isn't it?

**Comment by shioyama** [comment]
Ah yes, that is a documentation issue! Thanks very much for noticing. Would you like to make a PR to fix it? :smile:

**Comment by shioyama** [comment]
Actually, the documentation should say:

```ruby
Video.i18n { title.matches("BCC") }
```

You don't need to pass any arguments to the block if you're just calling attributes on that model.

**Comment by shioyama** [comment]
Or rather, for the model `Post`:

```ruby
Post.i18n do
  title.matches("foo").and(content.matches("bar"))
end
```

Please try that on your model and verify that it works. You can optionally use a block argument and call attributes on that argument (useful if you are nesting different model blocks).

**Comment by shioyama** [comment]
Ok I updated the docs. Let me know if you discover any bugs with this querying interface, it was just introduced in 0.7 and should be very powerful, but there are surely edge cases that are not yet correctly handled.

**Comment by samuelpismel** [comment]
Owww, that's nice! Even simplier and better! Thanks!
