### ISSUE TITLE
ActiveRecord dup method does not create a new instance of attribute_backend object

### ISSUE THREAD

**Issue by pablocrivella** [shioyama/mobility#25]
Given the following scenario

```ruby
class Model
  translates :title
end

m1 = Model.create(title: 'Title')
m2 = m1.dup
m2.title = 'Changed title' # This changes m1.title
m1.title # => 'Changed title'
m1.title_backend == m2.title_backend # => true
```

**Comment by shioyama** [comment]
Nice catch, I figured `dup` would cause problems. I'll look into it.

**Comment by pablocrivella** [comment]
@shioyama let me know if i can help

**Comment by shioyama** [comment]
@pablocrivella This should be fixed on master now, can you give it a try? If it fixes it for you I'll release a new version later this week.

**Comment by pablocrivella** [comment]
@shioyama I can confirm it fixes my issue! Thanks!
