### ISSUE TITLE
Column backend does not support pluck or select

### ISSUE THREAD

**Issue by wenderjean** [shioyama/mobility#275]
## Context

I'm using `column` backend strategy in mobility and I can perform queries based on my translated column using `find_by` and even `where` but what intrigues me is that `select` or `pluck` does not know how to handle my column name.

I'm not considering this a problem but in fact a feature not implemented, if there is an already approach to handle this I'm sorry for the issue but I really didn't find nothing about in docs and stackoverflow.

## Expected Behavior

I expect mobility to handle my column name when I use `select` or `pluck` methods.

```ruby
Mobility.locale = :jp
Post.all.pluck(:title) # select title_jp from posts
```

## Actual Behavior

```ruby
Post.all.pluck(:title) # ERROR:  column "title" does not exist
```

**Comment by shioyama** [comment]
> what intrigues me is that select or pluck does not know how to handle my column name.

I was actually thinking about this just a couple hours before you posted this issue. As it turns out, this is very easy to do now that querying has been [refactored into a plugin](https://github.com/shioyama/mobility/pull/216). I already added `order` [recently](https://github.com/shioyama/mobility/pull/261) which is actually slightly more complicated than methods like `select` or `pluck`.

The methods I think could be easily supported are any ones that accept an arel node, so e.g. `select`, `pluck` and `group` should work. Any other ones you can think of? This should take less than ten lines of code for all of them, and work for all backends.

**Comment by wenderjean** [comment]
@shioyama can i do this PR based on your previous one (#261) or are you already working on that?

**Comment by shioyama** [comment]
I just pushed what I have to the [add_new_query_methods](https://github.com/shioyama/mobility/tree/add_new_query_methods) branch, here is the commit: a79d724

I lightly tested it and it seems to work, but if you want to work on it from there please go ahead! It needs a few simple specs as well.

**Comment by shioyama** [comment]
Here's the code change, to discuss:

```ruby
%w[select pluck group].each do |method_name|
  define_method method_name do |*attrs|
    i18n_keys, keys = attrs.partition(&@klass.method(:mobility_attribute?))
      return super(*attrs) if i18n_keys.empty?

      base = i18n_keys.inject(self) { |query, key|
        @klass.mobility_backend_class(key).apply_scope(query, backend_node(key))
      }

      base.public_send(method_name, *(keys + i18n_keys.map(&method(:backend_node))))
    end
  end
end
```

As you mentioned, similar to `order` (#261) with the difference that `pluck` returns values, not a relation, so the method itself has to be called *last* with all the arguments.

Basically, what this does it two things:

1. Call `backend_class.apply_scope` for all translated attributes (this is necessary to join translations for KeyValue and Table backends)
2. Swap all translated attribute names for their respective Arel nodes (`keys + i18n_keys.map(&method(:backend_node))`

One thing I noticed is that the Table and KeyValue backends will default to using an INNER join here, which I think is not really appropriate (it will not include any results which have no translations in `Mobility.locale`). But this can be fixed separately in another PR.

**Comment by shioyama** [comment]
Merged #284, so this is now half-solved on the master branch.

**Comment by shioyama** [comment]
`select`, `group` and `pluck` are all supported now on the master branch. I'll release a new version soon.

**Comment by shioyama** [comment]
Released in 0.8.2, and supported on all backends. Let me know if you notice any issues.

**Comment by wenderjean** [comment]
Sure, thanks for the support :)

**Comment by borisrorsvort** [comment]
@shioyama seems this bug is back in `mobility (1.2.9)`
<img width="531" alt="Capture d’écran 2022-08-18 à 11 07 02" src="https://user-images.githubusercontent.com/39081/185356797-8d7a44e7-4d3a-410a-85de-55822631b573.png">
