### ISSUE TITLE
How find only by locale?

### ISSUE THREAD

**Issue by xxx44yyy** [shioyama/mobility#286]
this not working:
```
all_de_posts = Post.i18n.find_by(locale: :de)
```

**Comment by shioyama** [comment]
Please ask on stackoverflow or somewhere else, issues are for bugs/feature requests.

**Comment by xxx44yyy** [comment]
> Please ask on stackoverflow or somewhere else, issues are for bugs/feature requests.

I don't know if it's possible, so I wanted to check with the authors.

**Comment by xxx44yyy** [comment]
@shioyama
