### ISSUE TITLE
Backend writes are lost when performed in ActiveRecord transaction

### ISSUE THREAD

**Issue by Quintasan** [shioyama/mobility#312]
## Context
Rails 5.2.2
PostgreSQL 9.6

Backend: `:container`
Column type: JSONB

Model definition:
```ruby
class Survey < ApplicationRecord
  extend Mobility
  translates :welcome_text, :finish_text
end
```

## Test case
```ruby
require 'test_helper'

class SurveyTest < ActiveSupport::TestCase
  setup do
    ActiveRecord::Base.transaction do
      survey = Survey.create!
      survey.welcome_text_backend.write(:de, "Willkommen!")
      survey.welcome_text_backend.write(:pl, "Welcome!")
    end
  end

  test "translations are not empty" do
    survey = Survey.last
    assert_not_equal({}, survey.translations)
  end
end
```

## Expected Behavior
Changes made via `<attribute>_backend#write` method in a transaction should be saved

## Actual Behavior
The test case fails

## Additional information

A repository with a simple application demonstrating the issue can be found at https://github.com/Quintasan/mobility_transaction_issue

**Comment by shioyama** [comment]
`write` does not persist changes, you need to call `save` on the model to do that (whether in a transaction or not).

The readme [mentions this](https://github.com/shioyama/mobility#-getting-and-setting-translations):

> Internally, all methods for accessing translated attributes ultimately end up reading and writing from the backend instance this way. (The `write` methods do not call underlying backend's methods to persist the change. This is up to the user, so e.g. with ActiveRecord you should call `save` write the changes to the database).

**Comment by Quintasan** [comment]
@shioyama Uh, thanks I'm blind apparently

**Comment by shioyama** [comment]
You weren't the first to be confused by this! See #68. I later tucked the comment away so it's not so prominent in the readme -- maybe that was a mistake.
