### ISSUE TITLE
Working with ActiveAdmin

### ISSUE THREAD

**Issue by Quintasan** [shioyama/mobility#316]
I'm trying to use Mobility in my Rails application with ActiveAdmin as administration panel.
I use KeyValue (JSONB to be exact) backend.
I also have `activeadmin_json_editor` gem installed so it's not possible to produce bad JSON.
Inside my admin resource I permit `:translations` attribute using StrongParams.

This results in the following parameters
```ruby
2.5.3 (#<Admin::QuestionsController:0x00007fd466a9a690>):0 > permitted_params
=> <ActionController::Parameters {"utf8"=>"✓", "_method"=>"patch", "authenticity_token"=>"DwSuN9M9cD27dR7WmitBSMKKgVjhW1om3xwxOJUhK41no8RWH1Xh6L9QNIhOc1NhPYtm5QnKJWh7KEIUvuehUQ==", "commit"=>"Update Question", "id"=>"37", "question"=><ActionController::Parameters {"translations"=>"{\"en\":{\"body\":\"dupa\"}}", "dimension_id"=>"6"} permitted: true>} permitted: true>
```

However once I do `resource.update(permitted_params["question"])` my model has no translations at all.

```ruby
2.5.3 (#<Admin::QuestionsController:0x00007fd466a9a690>):0 > resource.update(permitted_params["question"])
   (0.4ms)  BEGIN
  ↳ (pry):18
  Dimension Load (0.4ms)  SELECT  "dimensions".* FROM "dimensions" WHERE "dimensions"."id" = $1 LIMIT $2  [["id", 6], ["LIMIT", 1]]
  ↳ (pry):18
   (0.3ms)  COMMIT
  ↳ (pry):18
=> true
2.5.3 (#<Admin::QuestionsController:0x00007fd466a9a690>):0 > resource
=> #<Question:0x00007fd45c284d98
 id: 37,
 body: nil,
 translations: {},
 created_at: Wed, 16 Jan 2019 12:17:38 UTC +00:00,
 updated_at: Fri, 08 Feb 2019 12:07:00 UTC +00:00,
 dimension_id: 6>
```

What am I doing wrong? Should I parse the JSON from the params and use `resource.<attribute_name>_backend.write` for each locale?

**Comment by shioyama** [comment]
> I use KeyValue (JSONB to be exact) backend.

KeyValue and Jsonb are two different backends.

> Inside my admin resource I permit :translations attribute using StrongParams.

`translations` is used by the Container backend, so I guess you're using that (Jsonb and KeyValue are different).

In any case, please post to StackOverflow with the `mobility` tag; issues are for bug reports. Thanks!
