### ISSUE TITLE
Set fallbacks option as array or just single locale

### ISSUE THREAD

**Issue by molfar** [shioyama/mobility#317]
Is it possible to set fallbacks option like :en or [:en, :fr]? 

Referencing these docs, It sounds tight.
https://github.com/shioyama/mobility/blob/b175fc56fd50bcdfd03a5043d82037eaa649afcd/lib/mobility/plugins/fallbacks.rb#L30-L34

But I tried so - and it does not work as expected. Option fallbacks only works like hash or boolean true.
I found these snippet that breaks referenced above docs.

https://github.com/shioyama/mobility/blob/b175fc56fd50bcdfd03a5043d82037eaa649afcd/lib/mobility/plugins/fallbacks.rb#L156-L164

So it would be nice to be able to set fallbacks as single locale or array, just like in I18n module.

**Comment by shioyama** [comment]
Issues are for bugs, please post to stackoverflow or gitter.

**Comment by molfar** [comment]
It looks like a bug, because setting fallbacks not working as declared in docs.

**Comment by shioyama** [comment]
No, the docs are referring to passing `fallback:` as an option to the accessor, i.e.

```ruby
post.title(fallback: :en)
# uses `:en` as the fallback for this read
```

**Comment by molfar** [comment]
Ok, I understood. But why we cant set default (global) **fallbacks** as single locale (or array)? It is difficult to construct a whole hash when you have 18 locales in you app and then keep them synced with I18n.available_locales.

**Comment by shioyama** [comment]
> Ok, I understood. But why we cant set default (global) fallbacks as single locale (or array)?

Fair enough, you could do something like:

```ruby
Mobility.configure do |config|
  # ...
  Mobility.default_options[:fallbacks] = Hash.new([:en, :ja])

  # ..
end
```

By passing an argument to `Hash.new` the hash will always default to that value, so any key called on the hash will return the array (in this case `[:en, :ja]`). Which is basically what you want, right?

**Comment by molfar** [comment]
@shioyama  Just now experimented with your suggestion, hash with default value - fallbacks does not works with this method:

`config.default_options[:fallbacks] = Hash.new([:en, :ja])`

but setting it explicitly as hash work as expected:

`config.default_options[:fallbacks] = { fr: :en }`

So, my previous comment is still actual.
