### ISSUE TITLE
Undefined method `backend' when using mobility_accessor

### ISSUE THREAD

**Issue by leemcd56** [shioyama/mobility#318]
## Context

I am trying to use **mobility** in a new gem (meant only for the company that is developing it) that will also implement translation versioning using **paper_trail**. In the method meant to proxy `translates` I use the dynamic field passed to the method to try and access the backend so that I can have better control of the output.

This is the [Gemfile.lock](https://gist.github.com/leemcd56/edd7f434fc61e75481930f2dab8bf4f0) for the project.

### `lib/xyz.rb`

```ruby
module XYZ
  def self.extended(base)
    base.extend Mobility
  end

  class << self
    extend Mobility::Translates

    def locale=(locale)
      Mobility.locale = locale || I18n.default_locale
    end
  end

  def translate_method(field, **options)
    mobility_accessor field do
      puts "Field #{field} is being accessed"
    end
  end
```

### `app/models/center.rb`

```ruby
class Center < ApplicationRecord
  extends XYZ

  translate_method :name, type: string, fallbacks: { :'fr' => 'en' }, locale_accessors: true
```

### Output

```bash
Started GET "/api/v1/centers?language=fr" for ::1 at 2019-02-12 13:00:18 -0600
Processing by Api::V1::CentersController#index as */*
  Parameters: {"language"=>"fr"}
Completed 200 OK in 756ms (ActiveRecord: 0.0ms)

Field foo is being accessed
```

### Output

```
NoMethodError

undefined method `backend' for #<Attributes (key_value) @names=name> Did you mean? backend_name

  Extracted source (around line #105)

  mobility_reader field do
    puts "Field #{field} did a thing
  end
```

---

**Note:** When simply passing the params to `translates`, it works as expected but one cannot have access to the field backend that `mobility_accessor` is said to provide:

```ruby
def translate_method(field, **options)
  translates field, **options, default: lambda { self[field].to_s }
end
```

## Possible Fix

n/a

**Comment by shioyama** [comment]
```ruby
mobility_reader field do
  puts "Field #{field} did a thing
end
```

I'm not really sure what you're trying to do here, but the block you pass to `mobility_reader` is for defining custom methods on the backend:

https://github.com/shioyama/mobility/blob/f78ec253950707b653f5340b4e3e0f43045b609d/lib/mobility/translates.rb#L6-L7

There is no bug here that I can see, so I'll close this.
