### ISSUE TITLE
Dirty tracking does not work with ActiveRecord > 6.0.0.beta.3

### ISSUE THREAD

**Issue by shioyama** [shioyama/mobility#323]
The internals of how AM::Dirty and AR::Dirty work were completely changed in rails/rails#35933 and now break Mobility entirely (see #322). I've made [a comment](https://github.com/rails/rails/pull/35933#issuecomment-485233818) asking whether a change to allow unpersisted dirty attributes on an AR model would be accepted. If that is not possible, it would mean that Mobility would have to hack the internals of ActiveRecord, which I *really* do not want to do.

Until then, this is a warning about the issue for anyone trying Mobility with Rails 6. If you want this to work, please comment on the rails PR linked above.

**Comment by shioyama** [comment]
Ok Rails 6 was released, this gets bumped priority. I'll dive into it sometime in the next few weeks.

**Comment by doits** [comment]
This is not a solution for every translation backend, but if you store the translations inside a json(b) column of your instance, you can basically follow what `ActiveRecord::Store` does: https://github.com/rails/rails/blob/6-0-stable/activerecord/lib/active_record/store.rb#L143-L177

Might become handy if you come to the conclusion to write different implementations for each translation backend.

**Comment by shioyama** [comment]
Re-opening since there are remaining issues and the current fix has not yet been released.

**Comment by shioyama** [comment]
Released 0.8.9 which fixes this issue. Closing!
