### ISSUE TITLE
Add support for versioning with paper_trail

### ISSUE THREAD

**Issue by jokrah** [shioyama/mobility#324]
## Context
At the moment, it's not possible to use paper_trail with mobility. We're using mobility with a table backend and paper_trail cannot save the changes. It should be considered to add support to versioning gems such as paper_trail. We switched from globalize to mobility because of performance issues. But as globalize is already supporting this feature, I hope versioning support can be added to mobility as well (https://github.com/globalize/globalize-versioning)

## Expected Behavior
Changes in models using mobility are saved in paper_trail as well.

## Actual Behavior
Changes in models using mobility are not saved in paper_trail db.

## Possible Fix
See https://github.com/globalize/globalize-versioning for a possible solution.

**Comment by shioyama** [comment]
Hi @jokrah, thanks for the suggestion. I contributed to globalize-versioning so I know the gem (it's actually very small).

I agree this would be a nice addition, unfortunately the priority for me right now is #323 and also on cleaning up and releasing a v1.0, so I don't think I will get to this anytime soon.

If you or anyone else wants to give it a try, I'm happy to provide help on it. The challenge with Mobility is always that ideally you want to support all backends, not just one backend. I managed to do that with both [friendly_id-mobility](https://github.com/shioyama/friendly_id-mobility) and [mobility-ransack](https://github.com/shioyama/mobility-ransack) so those may provide another reference point.

**Comment by shioyama** [comment]
I know it's  not related to this issue, but:

> We switched from globalize to mobility because of performance issues. 

What performance issues were those?

**Comment by shioyama** [comment]
Thanks @sedubois I will eventually look into it. Rails 6.0 compatibility is done but I'm working on a rewrite for an eventual v1.0 so that's still priority at the moment.

**Comment by sedubois** [comment]
@shioyama I just watched your RailsConf talk from last year (better late than never), was very interesting. This reminded me of this library. Are you still planning to bring PaperTrail support or develop other features or is the development on hold? Keep up the good work 😊

**Comment by shioyama** [comment]
Thanks @sedubois! Glad you enjoyed the RailsConf talk.

About PaperTrail support, I think you can safely assume I will not get to working on it anytime soon (if ever). I want to support Mobility with limited time, so I need to keep the core simple, and the more integrations there are the hard it will be to support everything.

Hope that makes sense :slightly_smiling_face:

**Comment by shioyama** [comment]
I'm actually not familiar enough with paper trail to really say, but the Globalize versioning gem is I believe quite minimal so it shouldn't be so hard.

There is a kind of API for extending Mobility, used by [mobility-ransack](https://github.com/shioyama/mobility-ransack) for example, but it's not documented. Making it clearer how to extend Mobility *is* something that I would be open to doing (and actually want to do).

**Comment by shioyama** [comment]
Actually the API for extending Mobility is one of the things that should be clearer with the release of v1.0. The master branch has a lot of changes that should make this more straightforward. But again, not documented other than in specs.

**Comment by shioyama** [comment]
I've created an issue in #366 to update inline docs on the changes in master to make it easier to develop extensions for Mobility v1.0.

**Comment by shioyama** [comment]
This is unfortunately not going to happen, so I'm closing this.

**Comment by haffla** [comment]
I know this is a dirty monkey patch. But this works for us. Maybe it is useful for someone else. We have it in an initializer.

```ruby
  require "mobility/backends/active_record/key_value"
  [:StringTranslation, :TextTranslation].each do |klass|
    Mobility::Backends::ActiveRecord::KeyValue.const_get(klass).class_eval do
      has_paper_trail
    end
  end
```

Now you can do

```ruby
word = Word.first
paper_trail_versions = word.string_translations.where(locale: :en).versions
```

At least you now have a history of changes to your translations.
