### ISSUE TITLE
Auto-loading the Sequel inflectors causes Rails autoloading to break

### ISSUE THREAD

**Issue by matiaskorhonen** [shioyama/mobility#325]
Loading the Sequel inflection support interferes with the inflections provided by ActiveSupport since both of them provide the same extensions to `String` (`#plural`, `#singular`, `#humanize`, etc) but with different implementations.

## Context

In our case we're using ActiveRecord for our main application but need Sequel to import some data from another database (but don't need Mobility support for Sequel).

We're using the Postgres JSONB backend.

* Rails 5.2.3
* Mobility 0.8.7
* Sequel 5.2.0

## Expected Behavior

Mobility should only enable/require backends that have been configured.

Currently there isn't a way I can easy stop Mobility from attempting to require Sequel, aside from forking the gem and modifying `lib/mobility.rb` directly.

It's also very confusing that if I have `gem 'sequel', require: false` in my Gemfile, Sequel still ends up being loaded because it's automatically required by Mobility.

## Actual Behavior

Every spec in our RSpec test suite fails because changing the inflection implementation changes where Rails tries to find code.

## Possible Fix

There should be a way of only loading the Mobility backends required, rather than automatically setting them all up as long as the required gems are available.

Possibly the Sequel inflection extension shouldn't be loaded at all if `ActiveSupport::Inflections` is present.

**Comment by shioyama** [comment]
Wow using Sequel and ActiveRecord together... that's not something I had imagined would ever happen. I'll have to think about this one, but:

> Possibly the Sequel inflection extension shouldn't be loaded at all if ActiveSupport::Inflections is present.

If you can make a PR doing this, and specs pass, I could merge/release it. I don't think there's a realistic case where you would want to load both of these, right?

**Comment by matiaskorhonen** [comment]
In this case we're using Sequel to import data from a legacy system, so it's a little weird but not a lot…

We also have another project where we have both ActiveRecord and Sequel where Sequel is used to connect to an external database using OBDC, but that project isn't using Mobility and so isn't affected by this.

I'll try to make time to create a PR for the inflections issue…

**Comment by shioyama** [comment]
Fixed in #326.
