### ISSUE TITLE
Support Rails Activerecord::Enum attributes?

### ISSUE THREAD

**Issue by molfar** [shioyama/mobility#337]
When I try to make Rails (ActiveRecord) enum attribute translatable, it breaks its enum functionality. There is some conflict with Mobility and  activerecord::Enum. https://api.rubyonrails.org/v5.2.3/classes/ActiveRecord/Enum.html

**Comment by shioyama** [comment]
Sorry, that's not really a priority right now. There are enough things to do for Rails 6 already. :smile:
