### ISSUE TITLE
How to get list of available accessors?

### ISSUE THREAD

**Issue by alec-c4** [shioyama/mobility#356]
Hi!
Is there any method to get list of all available translation accessors, something like globalize_attribute_names from globalize gem?

**Comment by alec-c4** [comment]
of course I can use something like 
```
I18n.available_locales.each {|l| "name_#{l.to_s}"}
```
but it look ugly :(

**Comment by shioyama** [comment]
Unfortunately there is no clean way to do this right now. The accessors are defined here:

https://github.com/shioyama/mobility/blob/97dea40722cf3a78097366e30ce7a09dcbe9bacc/lib/mobility/plugins/locale_accessors.rb#L57

There's nothing actually tracking their names once the methods have been defined.

**Comment by mKontakis** [comment]
That is something that I extensively use, I would love to see that implemented

**Comment by shioyama** [comment]
Hmm I'm not sure. You can do this with something like:

```ruby
module I18nLocaleAccessors
  def locale_accessor_names
    mobility_attributes.flat_map do |name|
      Mobility.available_locales.map do |locale|
        "#{name}_#{Mobility.normalize_locale(locale)}"
      end
    end
  end
end
```

Then just `extend I18nLocaleAccessors` from your model classes, or to make it global just:

```ruby
class ApplicationRecord < ActiveRecord::Base
  # ...
  extend I18nLocaleAccessors
end
```

Since it's quite simple to implement, I'm not really inclined to add it to the plugin unless there are others asking for it. :thinking:

**Comment by Splines** [comment]
> unless there are others asking for it.

We use it too at [MaMpf](https://github.com/MaMpf-HD/mampf) and came here migrating from [`globalize`](https://github.com/globalize/globalize) & [`globalize-accessors`](https://github.com/globalize/globalize-accessors). Thanks for your suggested solution, shioyama.

If anyone wonders how this change could look like in production-code, [here](https://github.com/MaMpf-HD/mampf/pull/609/commits/f486935776582160a036cb4f84c1c142ec5f8c20) are the changes I just made to our codebase.
