### ISSUE TITLE
Allow to assign translations in one go

### ISSUE THREAD

**Issue by JanStevens** [shioyama/mobility#361]
Hello,

We would like to assign the locales in one go so we can do (assuming `name` is translated)

```ruby
update(name_i18n: {en: 'English name', fr: 'French Name' })
```

## Context
We are using PostgreSQL with JSONB backend and on the frontend React and GraphQL. Our frontend allows to specify the translations of the attributes in one go and we send it as a Hash to the GraphQL 
mutation

```ruby
{ en: 'English Name', fr: 'French Name' }
```
## Current Solution
I've created a plugin to add this behaviour

```ruby
module Mobility
  module Plugins
    # Adds a +#{attribute}_i18n+ method so you can easily mass assign the property from a hash
    class I18nWriter < Module
      # Applies the plugin, method called by Mobility
      def self.apply(attributes, option)
        return unless option
        attributes.model_class.include(new(*attributes.names))
      end

      def initialize(*attribute_names)
        Array(attribute_names).each do |name|
          define_i18n_writer(name)
        end
      end

      private

      def define_i18n_writer(name)
        module_eval <<~RUBY, __FILE__, __LINE__ + 1
          def #{name}_i18n=(values)
            values.each { |locale, value| mobility_backends[:#{name}].write(locale, value) }
          end
        RUBY
      end
    end
  end
end
```

Could this be added to the gem? Seems like a useful addition

**Comment by shioyama** [comment]
Hi! Thanks for the question. It seems reasonable, unfortunately I don't have much time to look at this right now. I'm also not sure about the `_i18n` API, which could possibly conflict with existing columns/attributes that use that pattern.

Need to think about how this could be implemented... discussion would be appreciated if you have any ideas :smile:

**Comment by tuzz** [comment]
I'd find this very useful. I have some code that copies records from one table to another and a way to set all translations in one go would be helpful.

I wonder if there should also be an i18n reader method that returns the backend translations, for consistency:

```ruby
Article.first.text_i18n
#=> { en: "english translation", fr: "french translation" }

Article.first.text_backend.translations
#=> { en: "english translation", fr: "french translation" }
```

That would mean you could do:

```ruby
Article.first.update!(text_i18n: Article.second.text_i18n)
```

What do you think?

**Comment by nashbridges** [comment]
Isn't it the same problem as [batch form submission](https://github.com/shioyama/mobility/wiki/Using-Mobility-with-Forms)?
Given that `name` has `locale_accessors` the update would look like:

```ruby
update({name_en: 'English name', name_fr: 'French Name'})
``` 

Maybe not so elegant, but the big upside is that the "_i18n" private implementation is not exposed in the public API (so that you can safely swap the JSONB backend in the future).

**Comment by aykc** [comment]
If we have :jsonb backend I guess the easiest way to apply all translations at once is:
```ruby
hash = { en: 'English Name', fr: 'French Name' }
post.write_attribute(:name, hash)
```
