### ISSUE TITLE
has_many scopes with mobility attributes raises error

### ISSUE THREAD

**Issue by cilim** [shioyama/mobility#362]
## Context
ruby 2.6.5
rails 6.0.1
mobility 0.8.9

I have this setup
```ruby
class Lecture
  has_many :articles, -> { order(title: :asc) }
end

class Article
  extend Mobility
  translates :title, column_suffix: '_i18n'

  belongs_to :lecture
end
```

## Expected Behavior
The articles should be returned and sorted by the `title`.

## Actual Behavior
```
pry(main)> lecture = Lecture.first
pry(main)> lecture.articles
=> #<Mobility::Plugins::ActiveRecord::Query::QueryExtension:0x3ffd872059a8>
pry(main)> lecture.articles.first
ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column "title" does not exist
LINE 1: ...cles" WHERE "articles"."lecture_id" = $1 ORDER BY "title" AS...
                                                             ^
from /Users/cilim/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:672:in `async_exec_params'
Caused by PG::UndefinedColumn: ERROR:  column "title" does not exist
LINE 1: ...cles" WHERE "articles"."lecture_id" = $1 ORDER BY "title" AS...
                                                             ^

from /Users/cilim/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:672:in `async_exec_params'

pry(main)> lecture.articles.to_sql
=> "SELECT \"articles\".* FROM \"articles\" WHERE \"articles\".\"lecture_id\" = 4 ORDER BY \"title\" ASC"
```

**Comment by shioyama** [comment]
You need to use the `.i18n` scope (the query plugin does not monkeypatch `where` by default), see the [readme](https://github.com/shioyama/mobility/pull/357#issuecomment-577650913).

**Comment by shioyama** [comment]
Let me know if this helps, if so I'd like to close this.

**Comment by cilim** [comment]
Thanks for helping @shioyama!

> see the [readme](https://github.com/shioyama/mobility/pull/357#issuecomment-577650913).

This is a PR 😄 

> You may want to define a default_scope with it (described in the readme).

Tried like so:

```
class Article < ApplicationRecord
  extend Mobility
  translates :title, column_suffix: '_i18n', ransack: true
  default_scope { i18n }
end
```

still the same error occurs.

If I try calling the `i18n` scope in the lecture relationship:

```
class Lecture
  has_many :articles, -> { i18n.order(title: :asc) }, dependent: :destroy, inverse_of: :lecture
end
```

then it works ok, with or without the Article default scope.

I'm content with the scope solution you provided. Thank you very much! :)

As for the issue, you can close it if you don't think it needs investigation that it didn't work with the default scope defined in the `Article` model.

Cheers! 👋

**Comment by shioyama** [comment]
Ah sorry! Wrong link, I meant [this one](https://github.com/shioyama/mobility#querying).

And yes you would need the scope in the association as well. Glad that worked!
