### ISSUE TITLE
Disable I18n.locale when setting attribute values

### ISSUE THREAD

**Issue by b2e9f523** [shioyama/mobility#37]
Hello,

first of all, thanks for this great gem!

I would like to know, if there is a way to simply assign and save a hash to an attribute in such a way that this hash will NOT be stored under the current locales key?

The reason I want to do that is to assign multiple locale values using a nested form and update multiple translations at once.

I use a JSONB column to store translations.

```ruby
# I18n.locale = :en
# It should set the attribute simply to the given hash
some_post.description = {en:  'Hello World',  de: 'Hallo Welt'} 
some_post.save

# Actual JSONB column value:
{'en': {'en': 'Hello World', 'de': 'Hallo Welt'}}

# Expected JSONB column value:
{'en': 'Hello World', 'de': 'Hallo Welt'}
```

**Comment by shioyama** [comment]
Hi! You can access the actual column using `read_attribute` and `write_attribute`, so:

```ruby
some_post.write_attribute(:description, { en: 'Hello World', de: 'Hallo Welt' })
```

should work, I believe (for the jsonb backend).

**Comment by b2e9f523** [comment]
Thank you very much! Just checked and it works!
But makes saving data from nested forms bit cumbersome.

Would be great to have an option to just disable setting attribute values (at least when using the JSONB backend) based on current locale, so you have to explicitly use locale accessors to write data to an attribute:

```ruby
class Post
  translates :description, writeable: false, locale_accessors: [:en, :ja]
end

# Set attribute in standard way
some_post.description = {en:  'Hello World',  de: 'Hallo Welt'} 
some_post.save

# Read attribute based on current I18n.locale or Mobility.locale
# I18n.locale = :en

some_post.description
#=> 'Hello World'
```

**Comment by shioyama** [comment]
Actually, there is a way to do this. Instead of using `translates`, use `mobility_reader`, and mobility will only add a writer (no reader).

So:

```ruby
class Post
  mobility_reader :description, locale_accessors: [:en, :ja]
end
```

Give that a try :smile:

**Comment by b2e9f523** [comment]
Chris, this works perfectly! Exactly what I was looking for!
Thanks for your efforts!

**Comment by shioyama** [comment]
:smiley:
