### ISSUE TITLE
Support JSONB column type and query operators

### ISSUE THREAD

**Issue by sedubois** [shioyama/mobility#389]
I would like to be able to translate `jsonb` types in addition to the existing  `string` and `text` types.

## Context

I currently use Globalize in my Rails app to translate an attribute backed by a `jsonb` type in my Postgresql DB. This holds an array of strings whose contents vary with language.

When migrating to Mobility I would like to try using the key-value backend so I am primarily interested by a solution for this backend.

## Expected Behavior

```rb
class Word < ApplicationRecord
  extend Mobility
  translates :my_attribute, type: :jsonb
end
```

## Actual Behavior

This feature is currently unsupported, AFAIK, or maybe this is already supported and I just did not find it?

## Possible Fix

My guess is this?
- create a new migration `create_jsonb_translations`
- create a new class `Mobility::ActiveRecord::JsonbTranslation`

Can this somehow be generalized to other types?

**Comment by shioyama** [comment]
You're right that this is not supported explicitly, but implicitly I *believe* you can simply do as you say, create that migration (so you have the `mobility_jsonb_translations` table) and a corresponding class, `Mobility::ActiveRecord::JsonbTranslation`. The code does not prevent other types I believe, it just doesn't precreate other tables or classes.

This could perhaps be generalized, but I think maybe another solution would just be to document the requirements (table + class), then any type should be supportable with a little bit of work.

Would you like to write something about this to on wiki? Assuming it does in fact work, I've never actually tried it :sweat_smile:

**Comment by sedubois** [comment]
Thanks @shioyama for the suggestion, I will try that once I'm in a state where I can further experiment with changing to a key-value backend (I'm currently finishing migrating from Globalize so I'm using the table backend).

But actually, even with the table backend, the query operations specific to JSON are currently not supported. 

For instance, the following will raise `DRb::DRbRemoteError: PG::UndefinedColumn: ERROR:  column "legacy_urls" does not exist` even though I have declared `translates :legacy_urls` in my Post model:

```rb
Post.i18n.find_by("legacy_urls ? :url", url: legacy_url)
```

A workaround is to use `Post::Translation.find_by("legacy_urls ? :url", url: legacy_url).translated_model`. However AFAIK `Post::Translation` is specific to the `:table` strategy (this is how I had been doing it with Globalize, which I was hoping to get rid of).

Is there a way to make this work in a backend-agnostic way?

**Comment by shioyama** [comment]
Hi @sedubois 

> `Post.i18n.find_by("legacy_urls ? :url", url: legacy_url)`

This will never work with Mobility, under any circumstance. Mobility *does not parse strings*, it would be much too difficult and error-prone to do so.

The limitation here to text/string columns is absolutely not a hard one, but the limitation that Mobility cannot parse string queries will not change.

Instead, you should look to Arel queries, which *are* supported if you use `i18n` with a block (see the readme). This is something I want to support fully. The problem there is that ActiveRecord does not have great support for PG operators, so Mobility adds some for the json/jsonb and container backends. You might want to look to that as a reference.

**Comment by shioyama** [comment]
I'm closing this as it is not hard to translate types other than string and text with the KeyValue backend, it just requires creating the tables and defining the appropriate class(es).
