### ISSUE TITLE
Get a list of available locales

### ISSUE THREAD

**Issue by cbothner** [shioyama/mobility#39]
Is there a way to get a list of the locales in which a certain attribute has a value?  I'm using the postgres jsonb backend, and I know I could just do `@model.read_attribute(:title).keys`, but that seems brittle and like there ought to be a way that doesn't require me to know about the json blob structure.

**Comment by shioyama** [comment]
There isn't a way to do it currently, but you're right that it would be good to have something that any backend could use in the same way.

There are a few things like this that I've left out so far to focus on making sure the core of the gem works without issues, which it seems to do now, so I'm open to taking these kinds of feature requests. I'll keep note of this and in the next phase of work (probably in the next few weeks) think about how to implement them in a backend-independent way.

**Comment by jnylen** [comment]
@shioyama Any ETA?
I'm using jsonb.

Is it possible to like grab the jsonb data instead of only returning the language specific translation?

**Comment by shioyama** [comment]
You can always get the jsonb hash with `@model.read_attribute(:title)` if `title` is the attribute. As @cbothner noted, you can also get the locales with `@model.read_attribute(:title).keys`.

Of course this is jsonb-specific, other backends would have to be handled differently, and that's what I'm thinking about. Probably something like `@model.title_backend.locales`. I'm aiming to have that in for 0.2.0, which I'm working on. But if you need this now, just use `@model.read_attribute(:title).keys`, it should work fine as long as you don't switch backends.

**Comment by shioyama** [comment]
This has been merged into the `master` branch. Just call `post.title_backend.locales` to get the locales for the `title` attribute.

I'll be releasing 0.2.0 with a bunch of changes in the next day or so.

**Comment by shioyama** [comment]
@cbothner @jnylen 0.2.0 has been released, see the [changelog](https://github.com/shioyama/mobility/blob/master/CHANGELOG.md) and this [summary](http://dejimata.com/2017/8/13/mobility-0-2-now-with-plugins) of changes. You can now get available locales with `post.title_backend.locales`, etc.
