### ISSUE TITLE
Fallback local for sort if translated attribute is nil

### ISSUE THREAD

**Issue by aaronromeo** [shioyama/mobility#396]
If a translated attribute is nil in the current `Mobility.locale`, ideally the attribute value in fallback language would be used as a substitute in the `order by` clause.

## Context
I am currently using Mobility with Postgres (with a [Table backend](https://github.com/shioyama/mobility/wiki/Table-Backend)).

```
    mobility (0.8.10)
      i18n (>= 0.6.10, < 2)
      request_store (~> 1.0)
```

## Expected Behavior
This is an example of the expected behaviour
```ruby
class Category < ApplicationRecord
  extend Mobility

  translates :name, type: :string, fallbacks_generator: lambda {
                                                          I18n.available_locales.each_with_object({}) do |locale, memo|
                                                            memo[locale] = :'en-US'
                                                          end
                                                        }, locale_accessors: true

end
```

The data is seeded without a value in Spanish for `category1`
```ruby
category1 = Category.new
category2 = Category.new

Mobility.with_locale('es-MX') do
  category2.name = 'Puerco'
  category2.save
end

Mobility.with_locale('en-US') do
  category1.name = 'Mouse'
  category1.save

  category2.name = 'Pig'
  category2.save
end
```

The expected output uses the English fallback `name` for _Mouse_ as the Spanish `name` value is missing and English has been defined as the fallback locale.
```ruby
Mobility.with_locale('es-MX') { Category.i18n.order(:name).map(&:name) }
["Mouse", "Puerco"]
```

## Actual Behavior
The `order` attribute appears to resolve the `name` to `nil` when sorting. This moves `category1` to the bottom of the array.
```ruby
(byebug) Mobility.with_locale('es-MX') { Category.i18n.order(:name).map(&:name) }
["Puerco", "Mouse"]
```

## Possible Fix
It might be possible to fallback the locale using `COALESCE`.
```ruby
current_locale_table = "category_translations_#{Mobility.normalized_locale}"
Category.
  joins("LEFT OUTER JOIN \"category_translations\" \"category_translations_en_us\" ON \"category_translations_en_us\".\"category_id\" = \"categories\".\"id\" AND \"category_translations_en_us\".\"locale\" = 'en-US'").
  joins("LEFT OUTER JOIN \"category_translations\" \"#{current_locale_table}\" ON \"#{current_locale_table}\".\"category_id\" = \"categories\".\"id\" AND \"#{current_locale_table}\".\"locale\" = ").
  order(Arel.sql("COALESCE(#{current_locale_table}.name, category_translations_en_us.name)"))
```

**Comment by shioyama** [comment]
```ruby
translates :name, type: :string, fallbacks_generator: lambda {
                                                        I18n.available_locales.each_with_object({}) do |locale, memo|
                                                          memo[locale] = :'en-US'
                                                        end
                                                      }, locale_accessors: true
```

`fallbacks_generator` is not an option for the fallbacks plugin, so that option value is being ignored.

**Comment by shioyama** [comment]
Mental note: v1.0 should warn or raise on options that are not consumed by any plugin or backend.

**Comment by shioyama** [comment]
> If a translated attribute is nil in the current Mobility.locale, ideally the attribute value in fallback language would be used as a substitute in the order by clause.

This is similar to #51, but it's tricky and not really a priority right now, sorry. I'm going to close it because realistically it's not going to happen (anytime soon, anyway).

**Comment by aaronromeo** [comment]
@shioyama thanks for the clarification on `fallbacks_generator`. I misunderstood the docs.
