### ISSUE TITLE
Set fallbacks per request?

### ISSUE THREAD

**Issue by molfar** [shioyama/mobility#405]
I have a multi-country web app, and need to set different fallbacks schemas per each country.  Is it possible to set dynamic fallbacks per request, just like Mobility.with_locale ?

**Comment by shioyama** [comment]
This is basically #391 right?

**Comment by molfar** [comment]
Not exactly the same. My issue is about setting fallbacks dynamically and globally. Just like Mobility.with_locale works

**Comment by molfar** [comment]
I think it is related to I18n.fallbacks. Because there is not much sense without dynamic fallbacks there.

**Comment by timkrins** [comment]
Hi @molfar - I have done this in my own fork.
The usage is akin to
```
Mobility::Plugins::Fallbacks.with_fallbacks(fallbacks_override_array_or_false) do
   ...
end
```
I'll try create a PR over the weekend.

**Comment by sedubois** [comment]
I am also interested in having fallbacks only in a specific block, e.g.:
```
Mobility.with_fallbacks(fallback_config) do
  ...
end
```

**Comment by doits** [comment]
Just want to give a shout out to the plugin infrastructure of mobility. Once you grasp it, you can easily write your own fallback plugin to do exactly what you want. You can see my comment https://github.com/shioyama/mobility/pull/328#issuecomment-767024600 for two examples I am using. Maybe you can use it as a starting point for your own fallback plugin?

**Comment by shioyama** [comment]
I made some comments about how plugins can be used in https://github.com/shioyama/mobility/pull/328#issuecomment-945118378

https://github.com/shioyama/mobility/pull/538 is an attempt to make it a bit easier to create plugins without needing module builders (`< Module`) and/or included hooks.
