### ISSUE TITLE
Invalid single-table inheritance type

### ISSUE THREAD

**Issue by ArturLyapin** [shioyama/mobility#42]
Hello. Thanks for this gem. 
I have one problem, I can't use single-table inheritance with mobility gem.
Isolated reproduction here: https://gist.github.com/ArturLyapin/62669b79a0ab3a57ad2f563644f8e9e4

**Comment by shioyama** [comment]
Ok found the source of this problem, fix in #43. I also discovered a separate issue with the key-value backend with STI that I'll need to fix separately.

**Comment by shioyama** [comment]
Fixed in #43.

**Comment by ArturLyapin** [comment]
Yes, it works.
Thanks for the quick feedback.
