### ISSUE TITLE
fallback to whatever is left if the normal fallback results in a blank

### ISSUE THREAD

**Issue by zeitue** [shioyama/mobility#45]
I'm currently working with mobility and using two locales en and zh-CN but I have plans for about 50 or more locales to be added. Normally fallback would work like this zh-CN -> zh -> en, but in a case where there is only a field in zh-CN and the en one is blank how can I get this kind of behavior for 50 plus locales without defining fallback chains? 

Thanks

**Comment by zeitue** [comment]
This is how I figured to do this so far, but it seems hackish.

```
class Domain < ApplicationRecord
  include Mobility
  translates :namespace, type: :string, fallbacks: true

  def namespace_l
    if self.namespace.to_s.empty?
      self.read_attribute(:namespace).values.first
    else
      self.namespace
    end
  end
end

```

**Comment by shioyama** [comment]
(You're using the jsonb backend, right? In which case you don't need that `type: :string` option in there, that's only for key-value.)

I suppose you could do something like this:

```ruby
class Domain < ApplicationRecord
  include Mobility
  translates :namespace, fallbacks: true

  mod = Module.new do
    def namespace
      super || super(fallback: read_attribute(:namespace).keys.first)
    end
  end
  include mod
end
```

But this seems to have some odd behaviour trying it out now... I guess this ties into #39 - if you had a list of available locales (regardless of backend) then it would be easier to define fallbacks in terms of those.

I'll need to think about this a bit more...

**Comment by zeitue** [comment]
Yes I am using the jsonb backend, I've been thinking about this and it might actually be more of an I18n question over a question that actually pertains to Mobility. Thanks for the information about the `type: :string` I did not know that. I'm going to experiment some with the code sample and see how it works. Thanks again.

**Comment by shioyama** [comment]
I agree that it's a i18n fallbacks question. Probably you can default the fallbacks to use everything in `I18n.available_locales`. Anyway I'll close this.
