### ISSUE TITLE
Set a default to be used when there is no translation for a locale

### ISSUE THREAD

**Issue by cbothner** [shioyama/mobility#48]
I’m using the `jsonb` backend to translate an array. This is how it looks natively.
```ruby
translators: {"fr"=>["Foo Bar"]}
```

I want to be able to treat `translators` always as an array (calling `.to_sentence`), but I can’t do that if it returns `nil` when the locale is `en`. Is there any way to set a default like `[]`?

**Comment by shioyama** [comment]
You could do this by just overriding the attribute reader in your model, like this:

```ruby
def translators
  super || []
end
```

Then if the value is `nil`, it will fall through to `[]`.

I suppose assigning a default value when defining an attribute might be a useful thing to have... but in any case this should work for your use case I believe.

**Comment by cbothner** [comment]
Of course that works. I had been thinking that the original accessor was defined on the model, not its super, but of course that’s inherited from `ApplicationRecord` even if it’s coming from some fancy metaprogramming on that level. Thanks.

**Comment by shioyama** [comment]
Glad that works! And to be precise, the accessors are defined on a module that is included into your model when you call `transaltes`. See the api docs on the [Attributes](http://www.rubydoc.info/gems/mobility/Mobility/Attributes) class for details. So you can always override them in your model and call `super` to do custom stuff.

**Comment by shioyama** [comment]
@cbothner I've started a [default](https://github.com/shioyama/mobility/tree/default) branch with a new `default` option you can use when defining translated attributes:

```ruby
class Post
  include Mobility
  translates :title, default: 'foo'
end

post = Post.new(title: 'bar')
post.title
#=> 'bar'
post.title = nil
post.title
#=> 'foo'
```

You can also override it by passing a `default` option to the reader:

```ruby
post.title = 'bar'
post.title
#=> 'bar'
post.title = nil
post.title
#=> 'foo'
post.title(default: 'baz')
#=> 'baz'
```

I'll probably merge this in a day or two.

**Comment by cbothner** [comment]
Hey I totally appreciate the quick work (and the clarity on the chain of inheritance). I like that declarative API  much better than the (admittedly *sufficient*) workaround. I’ll reopen this so you can triumphantly close it when all the tests pass 😂
