### ISSUE TITLE
Allow fallbacks to be initialized at boot time

### ISSUE THREAD

**Issue by f1sherman** [shioyama/mobility#481]
First of all, thank you so much for this amazing library!

One thing I noticed recently, is that [the I18n fallbacks instance that is created for each attribute](https://github.com/shioyama/mobility/blob/f2ffbff3094dce0e085120d4c41f4eaf43246a9f/lib/mobility/plugins/fallbacks.rb#L145-L157) is lazy loaded. This is great for development, but in production, particularly with forking appservers, this can lead to increased memory usage and latency for the first request.

I was able to work around this with a monkey patch, but it would be great if something like [the railtie Rails uses to initialize i18n could be introduced](https://github.com/rails/rails/blob/71bc41477da96bb05edc33c1b6a42203e6999667/activesupport/lib/active_support/i18n_railtie.rb).

Thanks again!

**Comment by shioyama** [comment]
There are a bunch of issues around fallbacks:
- #405
- #309
- #328

Now that v1.0 has been released and the basic framework has stabilized, I'd really like to solve them all for 1.1 because fallbacks is such a popular feature, but I'm not actually a user of fallbacks myself so have a hard time seeing these issues. :thinking:

**Comment by shioyama** [comment]
Out of curiosity, what did your patch look like?

**Comment by f1sherman** [comment]
@shioyama I'm not sure how helpful my patch would be and I'm not authorized to share our source code. Instead I put together a WIP branch to help anchor the discussion. Hope this helps!

https://github.com/shioyama/mobility/pull/482

**Comment by eirvandelden** [comment]
I tested this out locally on our own project, where we are migrating from Globalize to Mobility 1.x during an upgrade to Rails 5.
The patch by f1sherman works in our case, what would be needed to get his PR merged?

**Comment by shioyama** [comment]
I don't have time to implement this, so closing.
