### ISSUE TITLE
Support for Trix

### ISSUE THREAD

**Issue by gudata** [shioyama/mobility#493]
It looks that mobility does not support the Trix editor for rails.

I tried to 
```

module ActionText
  class RichText < Record
    extend Mobility
    translates :body, type: :text
  end
end
```
but it didn't work. Any hints or wiki example will be welcomed.

**Comment by shioyama** [comment]
See https://github.com/shioyama/mobility/pull/412

This can't be done so simply, but @sedubois is working on a gem to do it. Changes coming in 1.1 will make it possible.
