### ISSUE TITLE
Suggestion for read me strong params

### ISSUE THREAD

**Issue by dvodvo** [shioyama/mobility#509]
The readMe page refers to tutorials.  Some points are dated but easily overcome - example: you've simplified the initializer to it bare minimum (nice!)

However establishing strong parameters is erroneous in at least one of the tutorials.  The following is quite succinct & would be pertinent:
```
      translated_params = (I18n.available_locales.map do |l|
        [:"title_#{Mobility.normalize_locale(l)}", :"general_information_#{Mobility.normalize_locale(l)}"]
      end.flatten)
      params.require(:word).permit( [...], translated_params)
```
Cheers!

**Comment by shioyama** [comment]
Thanks! The wiki is actually editable by anyone, please go ahead and edit the page:

https://github.com/shioyama/mobility/wiki/Using-Mobility-with-Forms
