### ISSUE TITLE
Query failing with with undefined method `mobility_attribute?`

### ISSUE THREAD

**Issue by DJA89** [shioyama/mobility#513]
There's a very very specific query that's failing with that error

`NameError: undefined method 'mobility_attribute?' for class`

the class in question does not extend mobility.

## Context
Here is a repo where you can reproduce this issue https://github.com/DJA89/mobility_issue

## Expected Behavior
The query should work with or without the i18n scope

## Actual Behavior
I have here an example of how the classes are and what specific query is breaking

```ruby
class ParkingLot < ActiveRecord::Base
  belongs_to :car, inverse_of: :parking_lots
  has_many :car_parts, through: :car
end
```
```ruby
class Car < ActiveRecord::Base
  extend Mobility

  translates :some_car_attribute, :some_other_car_attribute

  has_many :parking_lots
  has_many :car_parts

  default_scope { i18n }
  scope :some_car_scope, -> { where(some_thir_car_attribute: true) }
end
```

```ruby
class CarPart < ActiveRecord::Base
  extend Mobility

  translates :some_car_part_attribute

  belongs_to :car, touch: true

  default_scope { i18n }
end
```

Failing query:
```ruby
ParkingLot.includes(car: [:car_parts]).references(:car).merge(Car.some_car_scope).find_by(car_id: 8)
```

If I remove the `[:car_parts]` from the `includes` or the `merge` method from the query then the query works, but exactly as it's shown it fails with `NameError: undefined method 'mobility_attribute?' for class ` and it's trying to call the method for the class `ParkingLot`, the funny thing is the error looks correct, because `ParkingLot` does not extend Mobility, the question is why is it trying to call that method? We aren't even looking for any specific translated field. The query also works if I remove the default scope from the `Car` model.

```
NameError: undefined method `mobility_attribute?' for class `#<Class:0x00007f97a42fcc48>'
/Users/some_user/.rvm/gems/ruby-2.5.5/gems/mobility-1.1.1/lib/mobility/plugins/active_record/query.rb:164:in `method'
/Users/some_user/.rvm/gems/ruby-2.5.5/gems/mobility-1.1.1/lib/mobility/plugins/active_record/query.rb:164:in `block (2 levels) in <module:QueryExtension>'
/Users/some_user/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.5/lib/active_record/relation/finder_methods.rb:410:in `limited_ids_for'
/Users/some_user/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.5/lib/active_record/relation/finder_methods.rb:391:in `apply_join_dependency'
/Users/some_user/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.5/lib/active_record/relation.rb:550:in `block in exec_queries'
/Users/some_user/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.5/lib/active_record/relation.rb:584:in `skip_query_cache_if_necessary'
/Users/some_user/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.5/lib/active_record/relation.rb:547:in `exec_queries'
/Users/some_user/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.5/lib/active_record/relation.rb:422:in `load'
/Users/some_user/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.5/lib/active_record/relation.rb:200:in `records'
/Users/some_user/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.5/lib/active_record/relation/finder_methods.rb:504:in `find_take'
/Users/some_user/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.5/lib/active_record/relation/finder_methods.rb:103:in `take'
/Users/some_user/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.5/lib/active_record/relation/finder_methods.rb:81:in `find_by'
/Users/some_user/Projects/project_extras/mobility_issue/mobility_issue/lib/tasks/bad_query.rake:4:in `block (2 levels) in <top (required)>'
/Users/some_user/.rvm/gems/ruby-2.5.5/gems/railties-5.2.5/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/Users/some_user/.rvm/gems/ruby-2.5.5/gems/railties-5.2.5/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/some_user/.rvm/gems/ruby-2.5.5/gems/railties-5.2.5/lib/rails/command.rb:48:in `invoke'
/Users/some_user/.rvm/gems/ruby-2.5.5/gems/railties-5.2.5/lib/rails/commands.rb:18:in `<top (required)>'
/Users/some_user/.rvm/gems/ruby-2.5.5/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/some_user/.rvm/gems/ruby-2.5.5/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/some_user/.rvm/gems/ruby-2.5.5/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/some_user/.rvm/gems/ruby-2.5.5/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/some_user/.rvm/gems/ruby-2.5.5/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Users/some_user/Projects/project_extras/mobility_issue/mobility_issue/bin/rails:9:in `<top (required)>'
/Users/some_user/.rvm/gems/ruby-2.5.5/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
/Users/some_user/.rvm/gems/ruby-2.5.5/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
/Users/some_user/.rvm/gems/ruby-2.5.5/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
/Users/some_user/.rvm/gems/ruby-2.5.5/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
/Users/some_user/.rvm/gems/ruby-2.5.5/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
/Users/some_user/.rvm/gems/ruby-2.5.5/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
/Users/some_user/.rvm/gems/ruby-2.5.5/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
/Users/some_user/Projects/project_extras/mobility_issue/mobility_issue/bin/spring:15:in `require'
/Users/some_user/Projects/project_extras/mobility_issue/mobility_issue/bin/spring:15:in `<top (required)>'
```

## Possible Fix
I do not know the actual issue, I've found that even though the `ParkingLot` relation does not extend mobility, something makes it extend it for this query and it ends up calling `select` from Mobility instead of ActiveRecord. This happens [in this ActiveRecord method](https://github.com/rails/rails/blob/dc7364b1f39cf2fa3c3af3ea0f239f9ae1b5a790/activerecord/lib/active_record/relation/merger.rb#L67), but still haven't found why.

Update: See second comment.

**Comment by DJA89** [comment]
As an update, I created a repository where you can test it https://github.com/DJA89/mobility_issue. As the README says there is a task that runs the query or you can just call it yourself from the rails console. Adding this to the description above

**Comment by DJA89** [comment]
Update, I've "fixed" it by converting in the `%w[pluck group select]` methods this
```ruby
 return super(*attrs, &block) unless && attrs.any?(&@klass.method(:mobility_attribute?))
```
to
```ruby
return super(*attrs, &block) unless @klass.method_defined?(:mobility_attribute?) && attrs.any?(&@klass.method(:mobility_attribute?))
```

and adding to the `order` method that is giving me an error with a different query this in the first line
```ruby
return super unless @klass.method_defined? :mobility_attribute?
```
I do not particularly like this solution as they aren't tackling the real root, and I really am not sure if this doesn't break a different thing or if there's some other reason this is failing, it _seems_ like everything works fine like this.

**Comment by shioyama** [comment]
Thanks for the detailed report! This is the first time I've seen this. I'll look into it soon but the fix above would also be my first idea for a quick fix until something better is found.

**Comment by shioyama** [comment]
Ok, this _seems_ to be a problem that is present in 5.2, 6.0 and 6.1, but _not_ in 7.0 (not released yet). So I can make a fix which checks `respond_to?(:mobility_attribute?)` up to 6.2 but not >= 7.0.

**Comment by shioyama** [comment]
Actually never mind, there are two places to check `respond_to?(:mobility_attribute?)` and only _one_ of them is required in Rails 7.0, whereas previous to that _both_ are required.

**Comment by shioyama** [comment]
Fixed in [1.1.2](https://rubygems.org/gems/mobility/versions/1.1.2).

**Comment by DJA89** [comment]
Thanks! ❤️

**Comment by borisrorsvort** [comment]
@shioyama I’ve upgraded to 7.0.3 and i’m getting 
```bash
 undefined method `mobility_attribute?' for class `#<Class:0x00007fb00f1c3740>'
```

**Comment by shioyama** [comment]
Can you paste the stack trace?

**Comment by shioyama** [comment]
What's strange is that there is a regression spec which passes on AR 7.x:

https://github.com/shioyama/mobility/blob/b3420746e0ad7b2dea1d7fe13f2da6c513b93675/spec/mobility/plugins/active_record/query_spec.rb#L157-L194

So I'm confused why this isn't catching the issue :thinking:
