### ISSUE TITLE
Translating string attribute with multiple values (continued)

### ISSUE THREAD

**Issue by sedubois** [shioyama/mobility#517]
This is a follow-up to https://github.com/shioyama/mobility/issues/439 which was closed. I'm sorry to say, after re-reading the issues, I have not understood what is the recommended way to translate an attribute while allowing it to have several values? As much as possible I want to go with the defaults (i.e. using the KeyValue backend) and with the recommendations (i.e. avoiding JSONB which lacks uniqueness enforcement + has poor support in Mobility). How do other projects deal with this?

My concrete need is Posts each having several slugs. A post should be found by any of its slugs. For a given post, a specific slug is the "default" slug. All slugs are translated and they might not correspond between different locales.

Thanks so much for your help and sorry for the disturbance if this information is available somewhere!

**Comment by shioyama** [comment]
> avoiding JSONB which lacks uniqueness enforcement + has poor support in Mobility

Really? First time I heard that... :sweat_smile:

**Comment by sedubois** [comment]
> "poor support in Mobility" is still news to me

I intended to refer to the [comment](https://github.com/shioyama/mobility/issues/439#issuecomment-695147069) that it "is a rather unusual setup" and the observation that Mobility can only translate string and text types. It just feels like using JSONB is not encouraged and I am converging towards the same conclusion. I would prefer to do things the correct way, even if it means removing our current JSONB setup, hence having opened this question. What is the recommended/correct/canonical way to translate multi-valued string attributes?

**Comment by shioyama** [comment]
> I intended to refer to the comment that it "is a rather unusual setup" and the observation that Mobility can only translate string and text types.

This was about the KeyValue backend, because it requires tables per type, other backends tend to be easier or just work out of the box. e.g. json/jsonb work with any type.

**Comment by shioyama** [comment]
> It just feels like using JSONB is not encouraged and I am converging towards the same conclusion. 

Again, I don't know what you're referring to. Nothing discourages use of jsonb.

**Comment by sedubois** [comment]
Thank you @shioyama, so I will reconsider the decisions to migrate to KeyValue and stick to the Table backend (which we still use after migrating from Globalize) and will keep JSONB in spite of its lack of uniqueness enforcement.
