### ISSUE TITLE
Rails: `FrozenError - can't modify frozen attributes` when trying to update translations in `before_save` callback

### ISSUE THREAD

**Issue by dmtrjs** [shioyama/mobility#518]
## Context

Not sure if it's a bug or just a mistake on my side, but when I'm trying to update record's translations for different locales in `before_save` callback while passing two arguments to `translates :slug, :description` method, I get a `FrozenError - can't modify frozen attributes` error. When passing only one argument `translates :slug`, everything works fine and the record is updated.

Code example:

```
def generate_slugs
    Mobility.available_locales.each { |locale| generate_slug_for_locale(locale) }
  end

def generate_slug_for_locale(locale)
  Mobility.with_locale(locale) do
    self.slug = draft? ? SecureRandom.uuid : "#{title(locale)} #{I18n.t('for_sale', locale: locale)}".parameterize
  end
end
```

### Versions:
Ruby - 2.7.2
Rails - 6.1.3.2
Mobility - 1.1.2

## Expected Behavior

Record should be updated along with translations.

## Actual Behavior

`FrozenError - can't modify frozen attributes`

**Comment by shioyama** [comment]
Hmm that's strange. Mobility is pretty well-tested so this is either a corner case, or something else is affecting the result.

> When passing only one argument translates :slug, everything works fine and the record is updated.

That is very suspect. There is nothing in Mobility that would change depending on whether one or two attributes are defined in `translates`, so I'm guessing here there is something in your setup that is contributing to the attributes being different.

**Comment by shioyama** [comment]
Also: what backend are you using? And can you try switching it to a different one and see if the issue persists? Just to isolate whether it's backend-specific (almost certain it is).

**Comment by dmtrjs** [comment]
I'm using PostgreSQL. I'll get back to you if I'm able to reproduce it in a different backend.

**Comment by shioyama** [comment]
Closing unless/until this is reproducible.
