### ISSUE TITLE
forms for setting localized attribute values conflict between initializer and available_locales

### ISSUE THREAD

**Issue by dvodvo** [shioyama/mobility#521]
## Context
ruby '2.6.1'
gem 'rails', ' ~> 6.0.3', '>= 6.0.3.6 '
gem 'mobility', '~> 1.1', '>= 1.1.3'  (this strikeout is due to markdown just for this posting, no idea why...)
Using ActiveRecord

Mobility defines `    locale_accessors [:it, :en]`
rails defines
```
    config.i18n.available_locales = [:it, :en]
    config.i18n.default_locale = :en
    config.i18n.fallbacks = true
```

Applying Mobility to existing data table.

## Expected Behavior
This should be sufficient
```
  <% I18n.available_locales.each do |locale| %>
    <div class='cell small-6'>
      <%= Mobility.normalize_locale(locale) %>: <%= form.text_field "label_#{Mobility.normalize_locale(locale)}" %>
    </div>
  <% end %>

```
## Actual Behavior
```
  <% I18n.available_locales.each do |locale| %>
    <div class='cell small-6'>
      <%= Mobility.normalize_locale(locale) %>: <%= form.text_field "label_#{Mobility.normalize_locale(locale)}" %>
    </div>
  <% end %>
      <%= form.text_field :label %>

```
The non-localized field also needs to be set to submit and process the attribute's linguistic equivalence.

Processing by CategoryminorsController#update as HTML
`  Parameters: {"authenticity_token"=>"7iMZXuYFBSqiEt0tgFDyusR2s3sQeeqV2RjqVm53LSGpGIquWhGi7RT5CbVPEml072OhpEhJCfIAxf8vfW3cEg==", "categoryminor"=>{"name"=>"Icon", "categorymajor_id"=>"2", "label_it"=>"icona", "label_en"=>"icon", "label"=>""}, "commit"=>"Update Categoryminor", "id"=>"11"}`
processes
 ` Mobility::Backends::ActiveRecord::KeyValue::StringTranslation Create (0.7ms)  INSERT INTO "mobility_string_translations" ("locale", "key", "value", "translatable_type", "translatable_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"  [["locale", "it"], ["key", "label"], ["value", "icona"], ["translatable_type", "Categoryminor"], ["translatable_id", 11], ["created_at", "2021-08-21`

whereas:
`Processing by CategoryminorsController#update as HTML
  Parameters: {"authenticity_token"=>"cMcvvxqwq1Ws1+CwkR0kdZz642Tx69tFrTNvRO0YJ+ngOdr52kyuwtgwHcKR0ihaiG58eL0FxntSIwb/13tVSQ==", "categoryminor"=>{"name"=>"points", "categorymajor_id"=>"2", "label_it"=>"punti", "label_en"=>"", "label"=>"points"}, "commit"=>"Update Categoryminor", "id"=>"5"} `
processes both
```
  Mobility::Backends::ActiveRecord::KeyValue::StringTranslation Create (0.6ms)  INSERT INTO "mobility_string_translations" ("locale", "key", "value", "translatable_type", "translatable_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"  [["locale", "it"], ["key", "label"], ["value", "punti"], ["translatable_type", "Categoryminor"], ["translatable_id", 5], ["created_at", "2021-08-21 15:24:01.791331"], ["updated_at", "2021-08-21 15:24:01.791331"]]
  ↳ app/controllers/categoryminors_controller.rb:40:in `block in update'
  Mobility::Backends::ActiveRecord::KeyValue::StringTranslation Create (0.3ms)  INSERT INTO "mobility_string_translations" ("locale", "key", "value", "translatable_type", "translatable_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"  [["locale", "en"], ["key", "label"], ["value", "points"], ["translatable_type", "Categoryminor"], ["translatable_id", 5], ["created_at", "2021-08-21 15:24:01.794320"], ["updated_at", "2021-08-21 15:24:01.794320"]]
  ↳ app/controllers/categoryminors_controller.rb:40:in `block in update'

```
This can be overcome by throwing some logic in for the active locale, but that would be cumbersome and un-DRY.
This feels like a conflicting configuration issue.

**Comment by shioyama** [comment]
Sorry, I really can't make sense out of what you are asking here. There may be an issue but I don't see it. For general usage questions please use stackoverflow; if there is a bug or issue with Mobility itself, then it helps to have a failing test or something else which clearly demonstrates the problem.
