### ISSUE TITLE
v1.1.3 release tag missing?

### ISSUE THREAD

**Issue by valscion** [shioyama/mobility#522]
Hi! `mobility` continues to be really useful gem, so thank you for maintaining it! ☺️ 

I noticed that a few weeks ago v1.1.3 was released but it seems like a new tag or a release was never done for it? https://github.com/shioyama/mobility/releases

**Comment by shioyama** [comment]
Thanks for noticing! :heart: I just added the tag and a [release](https://github.com/shioyama/mobility/releases/tag/v1.1.3) for it now.
