### ISSUE TITLE
`bundle outdated` fails with mobility.gemspec error

### ISSUE THREAD

**Issue by brandondrew** [shioyama/mobility#537]
When I had Mobility 1.0.0.rc1, `bundle outdated` worked flawlessly.  Now it fails and complains about mobility.gemspec:

```
$ bundle outdated
Fetching https://github.com/shioyama/mobility.git

[!] There was an error while loading `mobility.gemspec`: undefined local variable or method `alpha' for Mobility::VERSION:Module. Bundler cannot continue.

 #  from /Users/brandon/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/bundler/gems/mobility-8873ccb0377c/mobility.gemspec:4
 #  -------------------------------------------
 #  $LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
 >  require 'mobility/version'
 #
 #  -------------------------------------------
```

## Context

I recently updated Mobility in my Rails app... here's the diff from my Gemfile.lock:

```
 GIT
   remote: https://github.com/shioyama/mobility.git
-  revision: 3a99bef27b1572962cb4f34edd33b8bb033de356
+  revision: 68ead91153ddcc9083943a743317cda2876bcfec
   specs:
-    mobility (1.0.0.rc1)
+    mobility (1.2.2)
       i18n (>= 0.6.10, < 2)
       request_store (~> 1.0)
```

I'm using Rails 6.0 with active record.

## Expected Behavior

I expected to see a list of outdated gems.

## Actual Behavior

Instead Bundler complained about Mobility.

**Comment by shioyama** [comment]
If you still have issues, try replacing `8873ccb0377cf11f09c5a92cdb14df3395afddbd` (the bad commit) in your `Gemfile.lock` with `bfc5506ae2b0c63579620381a0c3c28f20cb6b7c` (the fixed commit) and running again.

Closing since this should be fixed now.

**Comment by brandondrew** [comment]
Thanks for the super-fast turnaround!  👏🏻👏🏻👏🏻
