### ISSUE TITLE
custom primary_key not supported on model -- fails on i18n.find_by

### ISSUE THREAD

**Issue by benjamin-hg** [shioyama/mobility#541]
## Context
I want to translate a model (let's say `Article`) which has a primary key other than `id`, let's say `article_id` for example.

## Expected Behavior
When calling `Article.i18n.find_by(title: 'foo')`
The article with title "foo" is returned

## Actual Behavior

An error is thrown:

`ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column article.id does not exist`

## Possible Fix

See https://github.com/benjamin-hg/mobility/commit/5939dd3adcb9b595f90c1f5e7a340e7ef1bca099

**Comment by shioyama** [comment]
The fix in #541 seems great and super simple, thanks!
