### ISSUE TITLE
In Rails 7.0.0-alpha2, mobility and good_job seem to conflict using development puma web concurrency

### ISSUE THREAD

**Issue by leehericks** [shioyama/mobility#549]
## Context
Standard Rails new using Rails 7.0.0-alpha2 and Ruby 3.0.3 (same issue with 3.0.2)
Local Postgresql 12 database

Run `rails new testapp -d postgresql`

Edit puma.rb, uncomment (enable) web concurrency and preload_app! (cluster mode)

<img width="679" alt="Screen Shot 2021-12-03 at 10 43 02" src="https://user-images.githubusercontent.com/2021411/144530396-7caab2c5-f18c-4e94-86e8-68bdc7dbb2ff.png">

Add and configure either of mobility or good_job separately and no problem. But together is a problem.
[good_job setup](https://github.com/bensheldon/good_job#set-up)

Run `rails server`

## Expected Behavior
Be able to open 127.0.0.1:3000 in your web browser

## Actual Behavior
Browser hangs, request doesn't come through on the terminal.

## Workaround
Disable web concurrency and run Puma in single mode and then requests run properly. But of course this all works with Puma web concurrency in Rails 6.1.4.1, not sure what changed in Rails 7.0.0-alpha2

**Comment by shioyama** [comment]
Thanks @leehericks ! I have no idea what might be causing this, I've never heard of anything like this. I'll try to have a look at that repo.

**Comment by shioyama** [comment]
Ok, I've narrowed down the problem to this file

`lib/rails/generators/mobility/backend_generators/base.rb`
https://github.com/shioyama/mobility/blob/99579bb5f3bf9b3588fe5e7319bcb1b9e83131ec/lib/rails/generators/mobility/backend_generators/base.rb

**Comment by shioyama** [comment]
Honestly, this feels like a Rails bug.

**Comment by shioyama** [comment]
Fixed in 1.2.5.
