### ISSUE TITLE
Issue with Mobility as plugin dependency. Generators don't work.

### ISSUE THREAD

**Issue by a-barbieri** [shioyama/mobility#55]
I've been trying to use Mobility in my Rails plugin.

To reproduce the error create a new plugin:
```
rails plugin new my_plugin --mountable
```

If I run this from `my_plugin` root
```
rails generate mobility:install
```
it returns this error

> Could not find generator 'mobility:install'. Maybe you meant 'mobility:install', 'mobility:translations' or 'test_unit:system'

I also opened a [stackoverflow question](https://stackoverflow.com/questions/45241851/could-not-install-mobility-gem-on-rails-plugin)

**Comment by shioyama** [comment]
Hmm I didn't even know Rails had brought plugins back... I'll have a look. Thanks for posting the SO issue, I'll respond there.

**Comment by shioyama** [comment]
Ok I've reproduced the problem. I guess I'll need to jiggle those directories around a bit to get this to work.

**Comment by shioyama** [comment]
Made a PR to fix this in #56. @a-barbieri can you try the [fix_generators_location](https://github.com/shioyama/mobility/tree/fix_generators_location) branch?

**Comment by a-barbieri** [comment]
It works. Thank you. 

Let me know when you will public this update on the official gem so I can add it properly to my plugin gemspec. (Currently I cannot ship it along with the plugin but I have to manually add it to the application as Rails doesn't let you put unofficial gems in the gemspec file)

**Comment by shioyama** [comment]
Released [0.1.20](https://rubygems.org/gems/mobility/versions/0.1.20) which should fix the issue. Thanks for the report!

**Comment by shioyama** [comment]
@a-barbieri by the way, I'm presenting on Mobility in a couple weeks and would be curious about your use case. Are you building a CMS?

**Comment by a-barbieri** [comment]
Yes, spotted! 👍 
It's in alpha at the moment. At moment I'm concentrated on building the structure, preparing all tests and writing the documentation. I will concentrate on the design aspect once the code is stable. You can find it at [lacolonia/binda](https://github.com/lacolonia/binda).

I'm working on a plugin that will add the multi language feature. Once it's ready I'll give you a shout. ;-)
