### ISSUE TITLE
Eager loading translations breaks ordering of included associations

### ISSUE THREAD

**Issue by floydj** [shioyama/mobility#552]
Example project with a failing test: https://github.com/floydj/orderer

I have a Product model and Model model setup like the following:

```ruby
class Product < ApplicationRecord
  extend Mobility
  translates :title, type: :string

  has_many :models

  # display is an integer column on Model
  has_many :models_by_display, -> { order(:display) }, class_name: "Model" 
end

class Model < ApplicationRecord
  belongs_to :product
end

```

## Context

Using a base Rails 7.0.0 example app with Mobility 1.2.5, per the readme.

## Expected Behavior

Given the following test setup:
```ruby
  setup do
    @product = Product.create(title: "Something")
    Model.create(title: "one", product: @product, display: 1)
    Model.create(title: "three", product: @product, display: 3)
    Model.create(title: "four", product: @product, display: 4)
    Model.create(title: "two", product: @product, display: 2)
  end
```
Running this test should pass:

```ruby
  test "models_by_display with translations eager loaded" do
    assert_equal %w[one two three four],
      Product.i18n.includes(:models_by_display).eager_load(:string_translations).find(@product.id).models_by_display.pluck(:title)
  end
```
## Actual Behavior

Test output:
```
Failure:
ProductTest#test_models_by_display_with_translations_eager_loaded [/Users/jasonfloyd/code/rails/orderer/test/models/product_test.rb:18]:
--- expected
+++ actual
@@ -1 +1 @@
-["one", "two", "three", "four"]
+["one", "three", "four", "two"]
```

## Possible Fix

I don't have any fixes in mind, but [the full test file in the example project](https://github.com/floydj/orderer/blob/master/test/models/product_test.rb) shows that removing the eager loading from the query will cause the tests to pass.

**Comment by shioyama** [comment]
This has nothing to do with Mobility. You can take out the `i18n` in there and you get the same result:

```ruby
Product.includes(:models_by_display).eager_load(:string_translations).find(@product.id).models_by_display.pluck(:title)
#=> ["one", "three", "four", "two"]
```

So basically the problem is the `eager_load(:string_translations)`. Note that if you reload the model it works:

```ruby
Product.includes(:models_by_display).eager_load(:string_translations).find(@product.id).reload.models_by_display.pluck(:title)
#=> ["one", "two", "three", "four"]
```

It also works if you leave out the `includes(:models_by_display)`:

```ruby
Product.eager_load(:string_translations).find(@product.id).models_by_display.pluck(:title)
#=> ["one", "two", "three", "four"]
```

I haven't looked into the details but it's a question of how ActiveRecord handles ordering preloaded associations. I think you'd be better off rephrasing this as a more generic question about that to the Rails folks than asking here.
