### ISSUE TITLE
translated? method

### ISSUE THREAD

**Issue by r-obeen** [shioyama/mobility#553]
I have a hard time finding a solution for this :
I want to check if a record is translated for a certain language. For exemple, a method like such : `translated?(:en)`.

Does such a method exists ? Otherwise, any suggestions about how I could implement this ?

Thanks in advance

**Comment by shioyama** [comment]
Yep there's a class method for this, not well documented though (happy to accept a PR adding a note about it to the readme!):

```ruby
Post.mobility_attribute?(:title)
#=> true

Post.mobility_attribute?(:content)
#=> false
```

Having a `translated?` method would I suppose be nice, I just have tried in general to put as few instance methods on the model as possible by default (to avoid any possible collisions).
