### ISSUE TITLE
Unable to save record with counter_culture

### ISSUE THREAD

**Issue by michaelvu812** [shioyama/mobility#554]
I am using counter_culture(2.9.0). I can't save record because of error: can't write unknown attribute

Please refer to full error message below

```
Traceback (most recent call last):
        1: from (irb):21
ActiveModel::MissingAttributeError (can't write unknown attribute `comment_en_sg`)

    5  module ActiveModel
    6    class Attribute # :nodoc:
  148      private
  193        class Null < Attribute # :nodoc:
  206          def with_value_from_database(value)
❯ 207            raise ActiveModel::MissingAttributeError, "can't write unknown attribute `#{name}`"
  208          end
  211        end
  247    end
  248  end
```

**Comment by shioyama** [comment]
Sorry Mobility attributes are _not_ normal activerecord attributes, so you cannot expect every gem to be compatible with them.

**Comment by rbngzlv** [comment]
Landed here searching information about the error. Linking the PR opened in their moment by @michaelvu812 on the counter_culture project to play nice: https://github.com/magnusvk/counter_culture/pull/344
