### ISSUE TITLE
Support ISO 639-2 and  ISO 639-3 language codes

### ISSUE THREAD

**Issue by greena13** [shioyama/mobility#556]
## Context

Currently [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) (2 character) language codes [are being enforced](https://github.com/shioyama/mobility/blob/master/lib/mobility/plugins/fallthrough_accessors.rb#L39). 

## Expected Behavior

We need to support languages that are only expressible in [ISO 639-2](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) (3 characters).

## Actual Behavior

A method undefined exception is raised when attempting to use any of the dynamic accessor methods because the language code fails the regex used to enforce a valid code.

## Possible Fix

Change the regex to permit 3 character codes.

Clearly document in the Readme the expected/supported format of language codes.

**Comment by shioyama** [comment]
Happy to support this if you'd like to make a PR :grin:

**Comment by shioyama** [comment]
This is now fixed on the master branch, it'll be released in an upcoming 1.3 minor bump.
