### ISSUE TITLE
empty strings are getting converted to nil

### ISSUE THREAD

**Issue by systemnate** [shioyama/mobility#558]
## Context
Given a super generic default setup of `mobility` and this model:

```Ruby
class User < ApplicationController
  extend Mobility
  
  translates :name, type: :string
end
```

## Expected Behavior

I would expect name to be an empty string here:

```Ruby
user = User.new(name: "")
```

## Actual Behavior

`name` is `nil`:

```Ruby
user.name # => nil
```

I have `null` constraints on some fields, but I _do_ want to allow an empty string.  I don't think `mobility` should convert my value into `nil`.

This even happens with `column_fallback true`.

**Comment by systemnate** [comment]
Never mind!  I found it.  I just need to comment out the call to `presence` in `config/initializers/mobility.rb`.

**Comment by shioyama** [comment]
Yup, possibly that shouldn't be enabled by default.
