### ISSUE TITLE
Multiple backends - possible, not? How to import via CSV for jsonb type

### ISSUE THREAD

**Issue by dvodvo** [shioyama/mobility#562]
Investigating the possibility to handle multiple back-ends on a single application with multiple databases - under the assumption that each database would use only one given backend.

I also attempted to build an app using two backends; it appeared to work if the config file states `:key_value`, but in reality jsonb attributes were not being populated, everything ended up in the relevant translation table.

There are multiple issues here.
1) is it possible to use a backend for one database and another for a second?  How?
2) I cannot import data via CSV with a `jsonb` backend. (compounding the problem is that `jsonb` would be the fallback situation if the application were limited to a single backend - `:key_value` would not be an option)

## Context

Under `:key_value` a CSV import task:
```
Municipal.create(
  name: row[2],
  name_i18n_en: row[3],
  name_i18n_fr: row[4]
)
```
 imports the values by locale. *I also noticed via experimentation that stating `name_i18n: row[3]` would import to default locale*

When I decided to migrate back (removing the translation table migrations) and try `:jsonb` attributes backend, I had forgotten to re-set the backend to jsonb.  When importing jsonb data via CSV, a failure would occur `PG::UndefinedTable: ERROR relation "mobility_string_translations" does not exist"` I concluded that the backend definition is what generated the error.

with
```
Mobility.configure do
  plugins do
    backend :jsonb
[...]
```
and both the above task & a modified import task
```
Municipal.create(
  name: row[2],
  name_i18n: row[3]
)
```
fail.  
The import process complains with `No plugin configured for these keys: type. `
Changing the config to `backend :jsonb, type: :string` or `backend :jsonb, type: :json` does not change this behaviour.

## Expected Behavior

• be able to import values via CSV to the hash
• the error message might alos merit from being less cryptic, as the type does seem to be defined

**Comment by dvodvo** [comment]
The `No plugin configured for these keys: type.`error is resolved.  I had the model define `translates :name, type: :string` with the backend jsonb... the type definition is only applicable to key_value.  The error message is curious for this instance.  Thus the import can proceed with the initial syntax for the import task.

Remains the question of being able to have multiple backends for multiple database applications, but each db constrained to a single backend.

**Comment by jnylen** [comment]
@dvodvo you can pass in a custom backend per column via the `translates` function. Would that work?

**Comment by dvodvo** [comment]
Interesting suggestion.  However how would one go about this? I find no documentation that directly states how to assign a backend to and attribute. There is an oblique reference.  I interpret the ReadMe, specifically:
```
it can potentially be used to handle storing translations in other formats. [...]  
To use a custom backend, simply pass the name of a class which includes Mobility::Backend to translates:
```
the goal is not to invent a new backend, but leverage the existing ones.
While I fathom why a single db is best with a single backend, in the case of multiple databases, that logic holds water less effectively.

 I have documented my (evolving) thoughts on how to approach this [in this gist](https://gist.github.com/dvodvo/f7e3fac76e3db3d4adbc37448a8b709f)

**Comment by shioyama** [comment]
It's most definitely possible to use multiple backends together. You can even use different backends for different attributes.

As @jnylen mentioned, the API is just:

```ruby
translates :foo, backend: :table
translates :bar, backend: :key_value
```

etc

> is it possible to use a backend for one database and another for a second? How?

Not one per "database", one per _attribute_. You just specify the one you want by passing `backend` with the symbol for the backend you want.

**Comment by shioyama** [comment]
> The error message is curious for this instance. Thus the import can proceed with the initial syntax for the import task.

The error message is pretty clear: the KeyValue backend requires the `type` option and you hadn't set it, so it was telling you to set it.

Note also that Mobility also knows to disable other options for your default backend when you change the backend key. So if your default is `:key_value` and you have a global `type` defined in your configuration, and you change the backend to `:table`, it will know not to send that `type` option to the table backend (which would be wrong since Table doesn't take a `type` option).

I'd recommend looking at specs, this stuff is all tested and specs are the most accurate description of what Mobility does.

**Comment by shioyama** [comment]
Closing this, nothing here leads me to believe this is broken. If you have a clear example (two backends on the same model) where something is not working as expected, feel free to re-open.

**Comment by shioyama** [comment]
Also:

```
PG::UndefinedTable: ERROR relation "mobility_string_translations" does not exist
```

This is a missing table. You need to create tables for the KeyValue backend; this is all in the readme, and there is a generator for it.
