### ISSUE TITLE
json/jsonb backend doesn't work

### ISSUE THREAD

**Issue by alec-c4** [shioyama/mobility#571]
Hey!
I use json/jsonb columns for translations in my project, but it doesn't work right now. Let me show you some code

mobility.rb:
```ruby
Mobility.configure do
  plugins do
    backend :jsonb
    active_record
    reader
    writer
    backend_reader
    query
    cache
    fallbacks
    presence
    locale_accessors
    attribute_methods
  end
end

```

animal_kind.rb:
```ruby
class AnimalKind < ApplicationRecord
  extend Mobility
  translates :name, type: :string

  def to_s
    name
  end
end
```

On attempt to create instance of AnimalKind i see following error
```
irb(main):001:0> a = AnimalKind.new
/Users/alec/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/mobility-1.2.6/lib/mobility/pluggable.rb:51:in `validate_options': No plugin configured for these keys: type. (Mobility::Pluggable::InvalidOptionKey)
```

but when i change to `backend :key_value` - everything works fine.

version - mobility (1.2.6)

How to fix it?

**Comment by alec-c4** [comment]
@DJA89 yep, it works, but it worked with `type: :string` on another project, so it looks strange. But in this project i've changed backend to container, and it works fine

**Comment by shioyama** [comment]
`type: :string` is only for the KeyValue backend. I guess the error could be clearer.
