### ISSUE TITLE
jsonb backend doesn't find all `nil` values with `MyModel.i18n.where(my_internationalized_colmun: nil)`

### ISSUE THREAD

**Issue by DJA89** [shioyama/mobility#573]
## Context
Using Rails with ActiveRecord and Postgres, Mobility version 1.1.2.

```ruby
Mobility.configure do
  plugins do
    backend :jsonb, column_suffix: :_i18n
    ...
  end
end
```

```ruby
MyModel.i18n.where(my_internationalized_colmun: nil).count 
=> 1
MyModel.where("(my_internationalized_colmun_i18n ->> ?)::text IS NULL", I18n.locale).count
=> 2

MyModel.where("(my_internationalized_colmun_i18n ->> ?)::text IS NULL", I18n.locale).pluck(:my_internationalized_colmun_i18n)
 => [{}, {}]
 
 MyModel.i18n.where(my_internationalized_colmun: nil).to_sql
 => "SELECT \"my_models\".* FROM \"my_models\" WHERE NOT ((\"my_models\".\"my_internationalized_colmun_i18n\" ? 'en-US'))"
  
```

## Expected Behavior
When looking for `nil` values on translated columns, all records with a `nil` value should be returned.

## Actual Behavior
Only some of them are returned.

## Possible Fix
I am baffled

**Comment by shioyama** [comment]
This is some difference in how `?` works vs `->>` in postgres. I'm not an expert so unless you can say "This would be a better query for Mobility to make" I can't really help you on this.
