### ISSUE TITLE
Add querying in several/all translations simultaneously

### ISSUE THREAD

**Issue by john-999** [shioyama/mobility#575]
Currently, a query can look like this
```
City.i18n do
  name.matches("zurich")
end
```
If the current `locale` is `fr` (French), the above query would correctly find the city (b/c "Zurich" is the French translation of "Zürich").
If the current `locale` is `de` (German), the above query would NOT find the city (b/c Mobility only queries the translation of the current `locale`).

Therefor, it would be great to have a way to search in all the translations (`fr`, `de`, etc.) simultaneously, so the city would be found with any language the user may use to find the city.

**Comment by shioyama** [comment]
I appreciate the need, but feature requests are not really something I can handle right now.
