### ISSUE TITLE
validations failed

### ISSUE THREAD

**Issue by alec-c4** [shioyama/mobility#576]
Hey!
I'd like to add validations to my mobility-powered model, but it doesn't work

```ruby
I18n.available_locales.each do |locale|
    validates :"name_#{locale}", presence: true, uniqueness: {scope: :animal_type}
  end
```

Earlier i've used this code in another project and it worked fine

UPD: just to clarify: i see following error message "PG::UndefinedColumn: ERROR: column dictionaries_animal_kinds.name_en does not exist". My initializer's code:

```ruby
Mobility.configure do
  plugins do
    backend :container
    active_record
    reader
    writer
    backend_reader
    query
    cache
    presence
    locale_accessors
  end
end

```
UPD 2: I've tried with jsonb backend - the same result :(

**Comment by alec-c4** [comment]
I've identified my problem - it is because of `, uniqueness: {scope: :animal_type}`. Is it possible to use mobility with similar type of validations?

**Comment by charlesdeb** [comment]
I had the same issue - but I'm not using a scope:

```
class SessionType < ApplicationRecord
  extend Mobility
  
  validates :name, :order_by, presence: true

  I18n.available_locales.each do |locale|
    validates :"name_#{locale}", uniqueness: true
  end

  validates_uniqueness_of :name

  validates :name, uniqueness: true

  translates :name, backend: :action_text, plain: true

  default_scope { i18n }
end
```
I have tried all three of these attempts (not at the same time of course!) to validate uniqueness. All three result in postgres complaining that there is not a `name` (or a `name_en`) column in my `session_types` table. And there isn't one - I am storing `name` in the mobility table:

```
irb(main):399:0> st = SessionType.new(name: 'foo')
=> #<SessionType:0x00007f5f9931d350 id: nil, order_by: 10, created_at: nil, updated_at: nil>
irb(main):400:0> st.save!
  TRANSACTION (0.2ms)  BEGIN
  SessionType Exists? (0.8ms)  SELECT 1 AS one FROM "session_types" WHERE "session_types"."name" = $1 LIMIT $2  [["name", "foo"], ["LIMIT", 1]]
  TRANSACTION (0.1ms)  ROLLBACK
/home/some-path/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.4/lib/active_record/connection_adapters/postgresql_adapter.rb:768:in `exec_params': PG::UndefinedColumn: ERROR:  column session_types.name does not exist (ActiveRecord::StatementInvalid)
LINE 1: SELECT 1 AS one FROM "session_types" WHERE "session_types"."...
```
Does this give you more to go on @shioyama ?

**Comment by shioyama** [comment]
Hi @charlesdeb 

```ruby
  I18n.available_locales.each do |locale|
    validates :"name_#{locale}", uniqueness: true
  end
```

That won't work, Mobility's support for uniqueness validation is very specific/narrow: it will validate uniqueness of an attribute in the current locale. The best reference is the gem's own specs:

https://github.com/shioyama/mobility/blob/afeb067488f215cb469cfc9d7ad0a3853ae8ac5d/spec/support/shared_examples/validation_examples.rb#L2-L143

That's all that is tested so that's all that is supported (in all backends). I already kind of regret adding support for uniqueness validation because people expect it will just work like it does on any other attributes, but that's obviously not the case. Use it as-is or roll your own.

**Comment by shioyama** [comment]
Actually @alec-c4 I realize your original issue was also using locale accessors. Again, that won't work the way the plugin is designed. It looks for _mobility_ attributes, i.e. the base attribute, not localized accessors.

**Comment by madhums** [comment]
Umm not sure what's the issue but I am trying the same as described in the tests and yet the uniqueness validation fails (using rails 7.1.2).

```rb
# app/models/category.rb

class Category < ApplicationRecord
  extend Mobility
  has_many :stories, dependent: :restrict_with_exception
  validates :name, presence: true, uniqueness: true
  translates :name
end
```

```rb
# spec/models/category_spec.rb

describe Category do
    context "when name is not unique" do
      let!(:category) { create(:category) }
      subject { build(:category, name: category.name) }

      it { is_expected.not_to be_valid }
    end
end
```

**Comment by madhums** [comment]
Ah! Changing the order worked!

```rb
class Category < ApplicationRecord
  extend Mobility
  translates :name 
  validates :name, presence: true, uniqueness: true # must come after `translates`
end
```

**Comment by charlesdeb** [comment]
Nice work @madhums ! I will try that on my site and see if it makes a difference.
