### ISSUE TITLE
Defining relation on non-primary database of multiple-database application

### ISSUE THREAD

**Issue by dvodvo** [shioyama/mobility#586]
_note:  I am uncertain whether this is a feature that exists or not.  I assume it would be invoked in the initializer, but I fail to see the function_
## Context
An application with multiple databases.  
The databases are deemed to have different i18n value-definition mechanisms based on data creation/update context (centralised & distributed vs locally defined).
The key_value tables are to be set in distributed databases.

Running the install command `rails g mobility:install --database centraldata`
which respects the rails syntax for multiple database table generation [as provided in the rails guides](https://guides.rubyonrails.org/active_record_multiple_databases.html)  did not place the migrations in the `centraldata_migrate`directory as desired and expected.

Having moved the migrations to the desired `centraldata_migrate` directory and run the migrations for that directory, the migration process ran.

However, running tests on a model stored in the centraldata database returns an error when invoking a `translates` attribute  :
```
RuntimeError: Neutered Exception ActionView::Template::Error: PG::UndefinedTable: ERROR:  relation "mobility_string_translations" does not exist
LINE 9:  WHERE a.attrelid = '"mobility_string_translations"'::regcla...

<%= category_major.name_locale %>
```
The application, via the gem, seems unaware that the table exists, but in a seperate database.

## Expected Behavior

One should be able to define the database to connect to via the `mobility.rb` initialiser.

## Actual Behavior

See above.

## Possible Fix

By design, if the primary database is a distributed one, then there would be no issue.  
In the present instance this happens to be the case, but that is fortuitous.  And messy...

**Comment by shioyama** [comment]
I've never worked with an application with multiple databases, so I have no idea how to do this or what would need to change. You're welcome to post a PR with a proposed change to make things more concrete.
