### ISSUE TITLE
reader & locale_accessors won't return correct translation, but backend_reader does

### ISSUE THREAD

**Issue by hesslau** [shioyama/mobility#593]
## Context
When reading the translations (either using the reader or locale_accessors plugin), I'm not getting back what's in the translation table but instead the fallback values. When using the backend_reader, I'm getting the expected values.

Here's my initializer (using mobility 1.2.9)

````
Mobility.configure do
  plugins do
    backend :key_value
    active_record
    reader
    writer
    backend_reader
    query
    presence
    locale_accessors
  end
end
`````

The Model:

```
class User < ApplicationRecord
  ...
  extend Mobility
  translates :about_me, type: :text
  translates :slug, type: :string
  ...
end
```
## Expected Behavior
Readers and accessors should return the actual value from the key_value backend, same as the backend reader.
> user.about_me_de
> => "about de"

## Actual Behavior
Readers and accessors are returning the default value, not the translation

> user.about_me_de
> => "Saepe magni voluptatum." 

Which is the same as the default value (:en)

> user.about_me
> => "Saepe magni voluptatum."

Other variants are also returning the default value, even though :de is requested and present in the translation table.

> Mobility.with_locale(:de) { user.about_me }
> => "Saepe magni voluptatum."

> user.about_me(locale: :de)
> => "Saepe magni voluptatum."

When using the backend_reader, I'm getting the correct value.

> user.about_me_backend.read(:de)
> => "about de"

Here's what's in the database:

```
psql=# select * from mobility_text_translations;
 id | locale |   key    |  value   | translatable_type | translatable_id |        created_at         |        updated_at         
----+--------+----------+----------+-------------------+-----------------+---------------------------+---------------------------
  1 | de     | about_me | about de | User              |               1 | 2022-10-07 09:01:13.31457 | 2022-10-07 09:01:13.31457
```

## Possible Fix
At first I thought it could be an issue with the fallback plugins (I was using fallbacks and column_fallback before), but the issue persists even after disabling the plugins.

**Comment by hesslau** [comment]
Oh, since :en is my default locale I would be expecting to get the english value when requesting a translation which doesn exist (at least when the fallback plugin is enabled). So "default value" means the :en translation of the requested string.

**Comment by shioyama** [comment]
But your database as you've shown it has no English translation, so where is `"Saepe magni voluptatum."` coming from?

Anyway I need reproducible steps in order to consider this a bug of any kind. Ideally a failing test. See other issues to see how this is usually done. Otherwise it's not clear that we're even talking about the same thing.

Also, it seems like you have a `slug` translated attribute which has nothing to do with this issue. Please avoid everything unrelated and focus on reproducing the issue with as little as possible. That makes it easier to understand what's going on.

**Comment by hesslau** [comment]
> But your database as you've shown it has no English translation, so where is "Saepe magni voluptatum." coming from?
I had column_fallback enabled when making these examples but assumed it wasn't relevant, so I left it out from the configuration. "Saepe magni voluptatum." was stored in the original model's table

ok, after a bit of tinkering I figured out that my issue with locale_accessors was related to my rails configuration – begging your pardon for the confusion! 

however, I still can't get fallbacks to work, but I believe it's a configuration issue. posted it here: https://stackoverflow.com/questions/74113769/cant-get-fallbacks-to-work-in-rails-moblity

thanks for this awesome gem! this is helping a lot

**Comment by shioyama** [comment]
See: https://github.com/shioyama/mobility/issues/85
