### ISSUE TITLE
Model attribute defined fallback

### ISSUE THREAD

**Issue by dvodvo** [shioyama/mobility#595]
the application wants to be agnostic about the fallback locale, thus not define it in the initializer, and let it be driven by a user-set variable.

## Context
```
  gem 'mobility', '~> 1.2', '>= 1.2.6'
  gem "mobility-actiontext", "~> 1.1"
```
  initializer:
```
    backend :key_value
    active_record
    reader
    writer
    backend_reader
    query
    cache
    presence
    # fallbacks
    locale_accessors [:en, :cs, :de, :es, :fr]
```

defining a method  where `user_default = user.user_preference.default_locale`, the value of user_default renders as a string, but  
does not appear usable in the view having tried these variants sourced from the readMe document
```
<% if (article.title  locale: locale).blank? %>
  <%= article.title(locale: user_default.to_sym} %>
  <%= article.title(locale: user_default} %>
  <%= article.title_"#{user_default}" %>
...
```
How could this be achieved?

**Comment by shioyama** [comment]
Sorry this is not possible.

**Comment by dvodvo** [comment]
OK, fair enough.  

Assuming the available options  
• multitenancy
• view patch 
I have not tried the former, but I doubt this would be make sense.  Thus the best effective recourse would be a helper method patch (that sort checks the emptiness of default locale attribute and substitutes it with the content of the user_default attribute), yes?
