### ISSUE TITLE
Error when ordering and selecting distinct on translated resource

### ISSUE THREAD

**Issue by nciemniak** [shioyama/mobility#596]
## Context
Backend type: `backend :table`
Mobility version: 1.2.9
Relevant plugins enabled:
```
    ransack
    backend :table
    active_record
    backend_reader
    query
```

## Steps to reproduce
In the below example, the translatable resource is `Product`, and the translatable field on the resource is `name`, but you should be able to reproduce the error with any translatable resource.
```
product_collection = Product.i18n.order(:name).distinct
product_collection.first
```
Error occurs when trying to access any record from the collection (e.g. with `.first`):
```
ERROR:  for SELECT DISTINCT, ORDER BY expressions must appear in select list (PG::InvalidColumnReference)
```

This occurs because the `name` field from the translations table does not occur in the select list. I have tried to work around this by explicitly selecting this field from the translations table, like so:
```
Product.i18n.select("#{Product.table_name}.*, #{Product::Translation.table_name}.name")
```
but this does not work because the translation table is aliased when the actual SQL statement gets built.

Maybe there is an existing method that returns the value of the table alias? The only other workaround i see here is manually building out the translation table alias using the current locale, but it's not an ideal solution.

**Comment by shioyama** [comment]
Can you try:

```ruby
Product.i18n.select(:name).order(:name).distinct
```

?

**Comment by nciemniak** [comment]
Hey, thanks @shioyama, that helps a bit. It's still not ideal, since I'd like the query to return _all fields_ of the resource including the translated field(s) (therefore needing to explicitely add  `#{Product.table_name}.*` to the select clause), but it's still less messy than manually building out the translation table alias. For anyone else who has a similar issues, my workaround now looks something like this:
```
Product.i18n.select("#{Spree::Product.table_name}.*").select(:name).order(:name).distinct
```
