### ISSUE TITLE
Using a query method block does not automatically scope to i18n

### ISSUE THREAD

**Issue by nciemniak** [shioyama/mobility#599]
As described in the docs, you can pass a block to the query method and call attribute names from the block scope to build Arel predicates:
```ruby
Post.i18n do
  title.matches("foo").and(content.matches("bar"))
end
```

I would expect that setting `default_scope { i18n }` on a translatable resource class would allow for performing the same action without explicitly writing out i18n:
```ruby
Post do
  title.matches("foo").and(content.matches("bar"))
end
```

But it does not work. Is there any reason it needs to be scoped explicitly?

#### Relevant information
I am using plugin `query` and backend `table`.

**Comment by shioyama** [comment]
> But it does not work.

This is not a Mobility issue, it's a Ruby issue. `Post do` will be interpreted as calling the `Post` _method_ with a block, e.g.:

```ruby
def Post(&block)
  block.call("foo")
end

Post do |arg|
  puts arg
end
# puts "foo"
```

`default_scope` doesn't mean you can just pass a block and expect it to be caught by the scope.
