### ISSUE TITLE
Automatic ActionText `rich_text` detection failing when operating on locale-dependent mobility field

### ISSUE THREAD

**Issue by kalsan** [shioyama/mobility#601]
How to reproduce:

- Mobility has standard configuration, except for the backend, which is `:column`.
- Database columns of table `foos` are `bar_de` and `bar_en`, both of type text.
- Locales are handled via `fast_gettext` and the initializer states: `FastGettext.default_available_locales = %w[de en]`

```ruby
class Foo < ApplicationRecord
extend Mobility
has_rich_text :bar
has_rich_text :bar_de # required, or the forms will not work
has_rich_text :bar_en # required, or the forms will not work
```

Displaying `my_foo.bar` in a view will display the raw HTML. Displaying `my_foo.bar_de` or `my_foo.bar_en` will render the ActionText correctly.

Perhaps I'm doing something wrong, or is it a bug? Thanks in advance.

**Comment by shioyama** [comment]
Mobility doesn't support rich text fields out of the box. Try: https://github.com/sedubois/mobility-actiontext
