### ISSUE TITLE
Any accepted way to store images working with active storage ?

### ISSUE THREAD

**Issue by DavidGeismarLtd** [shioyama/mobility#602]
Is there any accepted way to store images/files for each different locale working smoothly with active storage ?

**Comment by shioyama** [comment]
Nope, I have never used activestorage and don't intent to do anything special to support it. You'll have to figure it out yourself.

**Comment by barnaclebarnes** [comment]
@DavidGeismarLtd I just released a gem here - https://github.com/barnaclebarnes/mobility_active_storage

We've just started using it internally and seems to work OK for our use case.
