### ISSUE TITLE
Unique Validation didn't work with locale_accessors on every locales

### ISSUE THREAD

**Issue by pominx** [shioyama/mobility#603]
## Context
Ruby 2.7.7
Rails 6.1.7.2
Database: PostgreSQL v14.5
mobility version: 1.2.9
backend :container (jsonb)
ORM: active_record
other plugins:
  - dirty
  - locale_accessors
 
I18n.available_locales = %i[zh-TW en]

I have a Category model with:
```
translates :name
validates :name, uniqueness: true
```

When I save/update an instance,
it only validates :name attribute with current locale.
But I use `locale_accessors` & use `:name_en`, `:name_zh_tw` in my form
I want to validate :name with both locales: :en & :'zh-TW' when submit form.
So I modify the validation to this:

```
validates :name_en, uniqueness: true
validates :name_zh_tw, uniqueness: true
```

## Expected Behavior
It should validate both locales since I enabled `locale_accessors`.

## Actual Behavior
But I got this error after update:

```
ActiveRecord::StatementInvalid in CategoriesController#update
PG::UndefinedColumn: ERROR: column categories.name_en does not exist LINE 1: SELECT 1 AS one FROM "categories" WHERE "categories"."name_e... ^

```

## Possible Fix
Maybe integrate `locale_accessors` into class UniquenessValidator?

**Comment by shioyama** [comment]
The uniqueness validator is already a stretch, I'm not making it any more complicated. If you want to validate all locales you'll need to define a custom validator for that.
