### ISSUE TITLE
accessor super method doesn't work with arguments like class.value(locale: :de)

### ISSUE THREAD

**Issue by Reocin** [shioyama/mobility#613]
I have created an accessor to parse my value from the string table from string to a boolean. 

I use the latest version of mobility with rails 7 and ruby 3.2.1.

## Expected Behavior
I have created an accessor to parse my value from the string table from string to a boolean.  Like:

```ruby
translates :lang_exist, type: :string

def lang_exist(*)
  super == "true"
end

def lang_exist=(value)
  super((value == true || value == 1 || value == "1") ? "true" : "false")
end
```

Then when i try to access a specific language on the following way:

`news.lang_exist(locale: :de)`

I get the following error:

`wrong number of arguments (given 1, expected 0)`

Has someone any idea what could be wrong here?

For now i use the `news.lang_exist_backend.read(:de)` method. it is working for now, but there i don't get the casting.

Thanks for your help

Regards

**Comment by shioyama** [comment]
You need to accept kwargs to your method, otherwise `locale: :de` is treated as a hash (which is why you get the `ArgumentError`):

```ruby
translates :lang_exist, type: :string

def lang_exist(**)
  super == "true"
end

def lang_exist=(value, **)
  super((value == true || value == 1 || value == "1") ? "true" : "false")
end
```
