### ISSUE TITLE
ordering by specific locale

### ISSUE THREAD

**Issue by dvodvo** [shioyama/mobility#614]
Take a translation application, a long list of words.  A study tool with multiple languages present (say in tabs - one per language).

The README specifies
```
You can also use methods like order, select, pluck and group on translated attributes just as you would with normal attributes, and Mobility will handle generating the appropriate SQL:
```

However this is somewhat incovenient when handling two languages side-by-side (the tabs).

The goal is to take the collection then sort it.  Using the README suggestion fails as it is based on a locale setting.
```
@words.i18n.order(element: :asc).in_groups_of(4, false) do |words|
```
whereas the ordering would be on a stated locale.

Is this possible?

**Comment by shioyama** [comment]
Unfortunately I don't have time to add new features to Mobility, although I can review them if folks submit PRs. I'll need to close this.

**Comment by dvodvo** [comment]
That's perfectly legitimate. It also confirms it is not possible at this time.
