### ISSUE TITLE
Add type checking plugin reference

### ISSUE THREAD

**Issue by GeorgeGorbanev** [shioyama/mobility#618]
Hi! Time ago I proposed type checking option for writer plugin in [this PR](https://github.com/shioyama/mobility/pull/590). It was rejected cause of limitation to add new functionality to gem. So I created my own gem with plugin. I will use it in couple of my projects and want to ask you to add link to my gem in readme/wiki/whatever to let people discover my gem too :) My gem is here: https://github.com/GeorgeGorbanev/mobility_typed 

Thank you!

**Comment by shioyama** [comment]
That's amazing, thanks for your work! Could you create a PR to add it to the "integrations" section of the readme? Thanks! :heart:

**Comment by GeorgeGorbanev** [comment]
Of course :) Here it is https://github.com/shioyama/mobility/pull/624

**Comment by shioyama** [comment]
Merged, thanks!
