### ISSUE TITLE
eager_load and pluck builds the wrong query

### ISSUE THREAD

**Issue by elcuervo** [shioyama/mobility#621]
## Context

First of all: Thank you for all your work on this gem.
It's our core framework for translations here at Unsplash and it made our extensions easy to implement.

Debugging some performance issues on produce I noticed that we were returning extra records during some relation calls.
Specifically `n` extra records as much as languages we have.

### Plugins

```ruby
Mobility.configure do
  # PLUGINS
  plugins do
    backend :key_value

    active_record

    reader
    writer

    column_fallback true

    backend_reader
    query
    cache

    presence
    fallthrough_accessors
  end
end
```

- We use the default backend and we are using [ to improve the calls](https://github.com/shioyama/mobility/wiki/KeyValue-Backend#eager-loading-and-avoiding-n1-queries).
- This bug affects calls with `pluck`.
- We also use `callback_column true` and `fallthrough_accessors`
- We add the `i18n` scope when the default locale is not in use.

## Expected Behavior

We should be getting the same records on the english version as with the other languages.

## Actual Behavior

When querying a relation with `pluck` we end up with extra records

![](http://share.elcuervo.net/Screen-Shot-2023-06-07-10-24-22.24.png)
I created this repo with a reproducible test https://github.com/elcuervo/mobility_bug/blob/main/test/models/post_test.rb

## Possible Fix

I don't know if is purely Mobility related or it has some ties with ActiveRecord.
I notice that the query being built as two `LEFT OUTER JOIN` instead of a secondary `INNER JOIN`.

### From the documentation:

![](http://share.elcuervo.net/Screen-Shot-2023-06-07-10-33-00.56.png)

### Executing the calls:

```ruby
Post Load (0.5ms)  SELECT "posts".* FROM "posts" ORDER BY "posts"."id" DESC LIMIT ?  [["LIMIT", 1]]
  Comment Pluck (0.5ms)  SELECT "Comment_text_es_string_translations"."value" FROM "comments" LEFT OUTER JOIN "mobility_string_translations" ON "mobility_string_translations"."translatable_type" = ? AND "mobility_string_translations"."key" = ? AND "mobility_string_translations"."translatable_id" = "comments"."id" LEFT OUTER JOIN "mobility_string_translations" "Comment_text_es_string_translations" ON "Comment_text_es_string_translations"."key" = 'text' AND "Comment_text_es_string_translations"."locale" = 'es' AND "Comment_text_es_string_translations"."translatable_type" = 'Comment' AND "Comment_text_es_string_translations"."translatable_id" = "comments"."id" WHERE "comments"."post_id" = ?  [["translatable_type", "Comment"], ["key", "text"], ["post_id", 2]]
```

**Comment by shioyama** [comment]
The support for quering is tricky, so once you start using things like `eager_load` you're really on your own. If you have an improvement to suggest, please make a PR to do that.
