### ISSUE TITLE
Empty content row is created in translation table.

### ISSUE THREAD

**Issue by leonardow-unep-wcmc** [shioyama/mobility#625]
## Context
I created a [new](https://github.com/leonardow-unep-wcmc/mobility_test) project for testing this issue.
This project [support](https://github.com/leonardow-unep-wcmc/mobility_test/blob/main/config/initializers/locale.rb) 6 locales.
Mobility config is [here](https://github.com/leonardow-unep-wcmc/mobility_test/blob/main/config/initializers/mobility.rb), which follow [Migrating from Globalize](https://github.com/shioyama/mobility/wiki/Migrating-from-Globalize) guide.

[Post](https://github.com/leonardow-unep-wcmc/mobility_test/blob/main/app/models/post.rb) is the only model in this testing project. It has a `before_save` callback, which loop all locales for the `content` value.

What I am trying to do is:
1. before save, fetch content in all locales
2. sanitize them to remove danger HTML code
3. reassign content (in all locales) with sanitized safe_content

In the testing project, I only implement step 1 in [line 11](https://github.com/leonardow-unep-wcmc/mobility_test/blob/main/app/models/post.rb#L11C7-L11C49).

If I run `Post.new.save` in Rails console, there will be 6 rows created in `post_translations` table. Which I expect 0 rows.
If I comment out line 11, and run `reload!; Post.new.save` in Rails console again, 0 rows is created in `post_translations` table.

Tested gem version 1.3.0.rc1 and 2.9.0.

## Expected Behavior
Nothing in the `post_translations` table, because `Post#content` is blank for all locales.
https://github.com/shioyama/mobility/wiki/Migrating-from-Globalize#blank-translations

## Actual Behavior
`post_translations` table has 6 locales rows, all content are NULL. 

## Possible Fix
Look like it only happen if I call locale specific accessors inside before_save callback.

**Comment by shioyama** [comment]
`Post#content` is blank, but Mobility memoizes and in doing so creates a translation record if you fetch a value. This is expected behaviour. If you'd like to change it, you can make a PR to propose that.
