### ISSUE TITLE
Not working properly with Rails 7.1.1

### ISSUE THREAD

**Issue by andersplanting** [shioyama/mobility#628]
I have a Rails app that I recently updated to 7.1.1. I've noticed that `Mobility` stopped working. When updating a model attribute the value doesn't change. And when creating a new record, the attribute remains `nil`.

## Context
Tested both with `v1.2.9` and `1.3.0.rc1`. Same problem for both versions. I use Postgres in my app. 

My model looks like this:

```
class Profession < ApplicationRecord
  extend Mobility

  translates :name, type: :string
end
```

If I comment out `translates :name, type: :string` it updates the attribute value.

## Expected Behavior
Should update attribute value on update and not have a nil value on create.

## Actual Behavior
See screenshot below for details:

<img width="1212" alt="Screenshot 2023-10-21 at 19 04 00" src="https://github.com/shioyama/mobility/assets/98227011/690eba8f-7e7b-4cdb-81a6-ee9f0c8bbba3">

**Comment by shido76** [comment]
Same for me, anyone else?
