### ISSUE TITLE
Allow composite foreign keys

### ISSUE THREAD

**Issue by mival** [shioyama/mobility#631]
## Context
Using table backend on active record (postgres)

## Expected Behavior
In translation method allow usage of compound foreign key, eg. article_type, article_id to eliminate usage extra unique column

## Actual Behavior
Method crash on 

1. [symbolizing keys](https://github.com/shioyama/mobility/blob/master/lib/mobility/backends/active_record/table.rb#L112)
2. [joining table](https://github.com/shioyama/mobility/blob/master/lib/mobility/backends/active_record/table.rb#L148)

 

## Possible Fix

1. check foreign key option for array, symbolize each item
2. check foreign key option for array create JOIN with AND SQL

**Comment by shioyama** [comment]
I posted on your PR, but if you can rebase it I'll merge and release it.

**Comment by hughevans** [comment]
I think unfortunately this does not work in Rails 7.1 and you need to use `query_constraints` instead.
