### ISSUE TITLE
Mobility with active_storage for translatable attachements

### ISSUE THREAD

**Issue by DavidGeismarLtd** [shioyama/mobility#633]
I would like to have translatable attachments for my active storage attachments in the same way I have translatable text, string attributes. Is there a way to make mobility work with active_storage ?

It would be great to have something like `has_one_translatable_attached :image ` for example.

I was not able to find this feature. Is there a way to achieve this ?

**Comment by shioyama** [comment]
Sorry, I can't support new features. You can create a separate gem for this, Mobility is flexible and documented (also with tests).

**Comment by rsmithlal** [comment]
Thanks for raising the question. I'd like to have localized customizable platform logos for my app. I will look into implementing something like this for the platform I am developing. 

The mobility-actiontext gem is probably a good source of inspiration for how to implement something like this.

https://github.com/sedubois/mobility-actiontext

**Comment by barnaclebarnes** [comment]
@rsmithlal @DavidGeismarLtd I just released a gem here - https://github.com/barnaclebarnes/mobility_active_storage

We've just started using it internally and seems to work OK for our usecase.
