### ISSUE TITLE
table fallbacks

### ISSUE THREAD

**Issue by ollym** [shioyama/mobility#642]
We migrated from Globalize today and were heavily dependent on fallbacks support for query, so wrote a simple initializer that brought the functionality back for the table backend.

```ruby
# config/initializers/mobility_extensions.rb

module MobilityQueryFallbacks
  extend ActiveSupport::Concern

  class FallbackAttribute < ::Arel::Nodes::NamedFunction
    include Mobility::Plugins::Arel::MobilityExpressions

    attr_reader :backend_class
    attr_reader :locale
    attr_reader :attribute_name

    def initialize(fallback_attributes, locale, backend_class, attribute_name)
      @backend_class = backend_class
      @locale = locale
      @attribute_name = attribute_name
      super('COALESCE', fallback_attributes)
    end
  end

  class_methods do

    def build_node(attr, locale)
      fallback_locales = I18n.fallbacks[locale]
      return super if fallback_locales.length == 1
      fallback_attributes = fallback_locales.map { |locale| super(attr, locale) }
      FallbackAttribute.new(fallback_attributes, locale, self, attr)
    end

    def join_translations(relation, locale, join_type)
      fallback_locales = I18n.fallbacks[locale]
      return super if fallback_locales.length == 1
      fallback_locales.reduce(relation) do |relation, locale|
        super(relation, locale, Mobility::Plugins::Arel::Visitor::OUTER_JOIN)
      end
    end
  end
end

ActiveSupport.on_load(:active_record) do
  require 'mobility/backends/active_record/table'

  Mobility::Backends::ActiveRecord::Table.prepend(MobilityQueryFallbacks)
end
```

Wanted to open a ticket as this doesn't feel far off a good solution, and would love to see this functionality added. What are your thoughts @shioyama on this as a general direction?

**Comment by BooVeMan** [comment]
I'm running in the same issue here, could this be implemented?

**Comment by shioyama** [comment]
The reason I've never tried to implement this is because it crosses a boundary between a plugin (fallbacks) which knows nothing about querying, with another plugin (query) which is all about querying. The query plugin would need to make assumptions about fallbacks and/or reach into the fallbacks plugin to do this.

In addition, this would be very tricky to do in a backend-agnostic way. The implementation here is based on the table backend, but Mobility should support fallbacks on other backends as well.

**Comment by shioyama** [comment]
My suggestion would be to make a small gem that is a new backend which extends the table backend and includes an option for fallbacks (separate from the fallbacks plugin).

**Comment by BooVeMan** [comment]
@shioyama thank you for explaining your reasoning.

**Comment by shioyama** [comment]
btw I looked into this a bit more, and although it would be doable, the implementation seems strange to me. `COALESCE` will return all the non-null values, so it's a "fallback" really but actually just returns all the results for any fallback locale. Is that how Globalize implements it?

**Comment by ollym** [comment]
@shioyama no `COALESCE` will return the first of the fallback values that is not null, and yes this is how globalize works. We've been running the code above in production at scale since I created this ticket and it's been really solid.
