### ISSUE TITLE
Saving a new record with a translated field in multiple locales should save the translations in a single query

### ISSUE THREAD

**Issue by sjieg** [shioyama/mobility#649]
I'm doing quite a large migration from an old translation system to Mobility. When running the scripts, it's having a heavy time inserting all the translations of every record (10 locales per record), because for every locale a query is triggered.

## Context

```Ruby
# config/initializers/mobility.rb
Mobility.configure do
  plugins do
    backend :key_value
    active_record
    query
    cache
    dirty
    fallbacks # config.i18n.fallbacks = [:en, :nl, :tr, :sr, :es, :ru, :de, :fr, :ua, :it, :pt, :pl]
    locale_accessors # config.i18n.available_locales = [:en, :nl, :tr, :sr, :es, :ru, :de, :fr, :ua, :it, :pt, :pl]
  end
end

# models/product.rb
class Product < ApplicationRecord
  extend Mobility
  translates :name, type: :string
end

# rails c
product = Product.new(name_en: "apple", name_nl: "appel", name_de: "apfel")
product.save!
```

## Expected Behavior

* Query1 saving the product record
* Query2 saving en, nl and de translation in a bulk insert

## Actual Behavior

* Query1 saving the product record
* Query2 saving en translation
* Query3 saving nl translation
* Query4 saving de translation

## Possible Fix

When using the active record plugin, potentially the Rails 6+ [method `insert_all `](https://blog.saeloun.com/2022/07/26/rails-6-insert-all/) could work.

---

Maybe the solution is way more complex than I imagine it, I tried having a look in the codebase, but I wasn't able to quickly find where this feature could potentially be added. Maybe with some pointers I could come back with a PR.

Final word: Great translation Gem, I'm loving it <3! I know I could solve this by manually writing insert queries, but I think this feature could be a nice addition to the gem.

**Comment by shioyama** [comment]
I don't think this would be easy to do. Mobility does this:

```ruby
class Product < ApplicationRecord
  has_many :string_translations, -> { where(key: ["name"]) },
    as: :translatable,
    class_name: Mobility::Backends::ActiveRecord::KeyValue::StringTranslation,
    inverse_of: :translable,
    autosave: true

    # ...
end
```

When you set attributes, you're essentially doing this:

```ruby
post.name = "foo"
# translation = post.string_translations.find { |t| t.key == "name" && t.locale == Mobility.locale }
# translation.value = "foo"
```

Then when you save the `Post` record, the `autosave: true` triggers all those associated records to be saved, causing all the `UPDATE` queries that you see.

Maybe the KeyValue backend could do something to make this all happen in an bulk insert in the `setup` block, but it would require careful thought. An alternative would be to bypass Mobility in this case and just execute the bulk insert yourself, if you know how things work (see above).

**Comment by shioyama** [comment]
I would be happy to accept a PR to do this, but I don't have time to do it myself.

**Comment by sjieg** [comment]
I appreciate the response. I'm in a similar situation with time to pick this up.

Would you be okay adding a dependency for this _problem_?

I'm thinking something in the lines of using [activerecord-import](https://github.com/zdennis/activerecord-import) and then use the [duplicate-key-update](https://github.com/zdennis/activerecord-import?tab=readme-ov-file#duplicate-key-update) feature:

```
post.name_nl = "foo"
post.name_en = "bar"
# translation = post.string_translations.find { |t| t.key == "name" && t.locale == Mobility.locale }
string_translations_hash = post.changed_languages.map {{key: "name", locale: _1.locale}}
# if MySQL version
Mobility::Backends::ActiveRecord::KeyValue::StringTranslation.import string_translations_hash , on_duplicate_key_update: [:value]

# if PostgreSQL version
Book.import string_translations_hash, on_duplicate_key_update: {conflict_target: [:key, :locale], columns: [:value]}

# Else fallback to default saving method
```
