### ISSUE TITLE
Can provide empty string despite validations

### ISSUE THREAD

**Issue by konradperlowski** [shioyama/mobility#661]
Since updating to 1.3, I can skip presence validations attached to translated properties. For example with such model:
```ruby
class Holiday
  extend Mobility
  translates :name

  validates :name_pl, presence: true
  validates :name_en, presence: true
end
```

I can do following:
```ruby
>> holiday.update("name_en" => "")
  TRANSACTION (0.2ms)  BEGIN /*application='Emh'*/
  Holiday Update (1.1ms)  UPDATE "holidays" SET "name" = '{"pl":"Holiday"}', "updated_at" = '2024-12-03 12:30:00.423685' WHERE "holidays"."id" = 1 /*application='Emh'*/
  TRANSACTION (2.4ms)  COMMIT /*application='Emh'*/
=> true
```

This works fine with such syntax:
```ruby
>> holiday.update(name_en: "")
=> false
```

## Context

I found this issue, as parameters returned from `permitted_attributes` [pundit](https://github.com/varvet/pundit) method returns hash in `{ "name_en" => "..." }` format, so with such controller:
```ruby
  def update
    if @holiday.update(permitted_attributes(@holiday))
      redirect_to holidays_path, notice: t(".success"), status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end
```
this test does not work:
```ruby
  test "should not update holiday" do
    patch holiday_url(@holiday), params: {
      holiday: {
        name_pl: "",
        name_en: ""
      }
    }

    assert_response :unprocessable_entity
  end
```
as controller proceeds with redirect after successful update.

This is migration file:
```ruby
class CreateHolidays < ActiveRecord::Migration[7.2]
  def change
    create_table :holidays do |t|
      t.jsonb :name, null: false, default: {}

      t.timestamps
    end
  end
end
```

## Expected Behavior

Updating required parameter with empty string should not be permitted.

## Actual Behavior

After updating `name_en` with empty string, it removes `en` key entirely from `name` hash:
```ruby
>> holiday.name_en
=> nil
```

**Comment by shioyama** [comment]
Has this changed from a previous version?

Note that the presence plugin does not prevent updating with empty strings, it simply converts blank strings to `nil`. The plugin is a single 50-line file, it's very simple and has not changed in years.

**Comment by shioyama** [comment]
You're going to have to give more details than this, I have no idea what else you have setup. Make a test that fails in 1.3 but passes in 1.2.9.

**Comment by shioyama** [comment]
Might be related to the change in jsonb db default values, please check the release notes.

**Comment by konradperlowski** [comment]
I created new project (rails 8.0.0, ruby 3.3.5), added mobility gem, installed and changed backend to `jsonb` and uncommented `locale_accessors` in configuration file.
Generated model with such migration:
```ruby
  def change
    create_table :holidays do |t|
      t.jsonb :name, null: false, default: {}

      t.timestamps
    end
  end
```

added validation to model:
```ruby
class Holiday < ApplicationRecord
  extend Mobility
  translates :name

  validates :name_en, presence: true
end
```

and such test works in 1.2.9, but does not work in 1.3.1 (or 1.3.0):
```ruby
  test "should validate name presence" do
    holiday = Holiday.create!(name_en: "name en")
    assert_not holiday.update(name_en: "")
  end
```
