### ISSUE TITLE
Version 1.3.1 has breaking changes (as well as 1.3.0)

### ISSUE THREAD

**Issue by kapso** [shioyama/mobility#662]
```ruby
class Blog < ApplicationRecord
  extend Mobility

  translates :title, dirty: true
end


blog = Blob.new
blog.title

(irb):5:in `<main>': undefined method `[]' for nil (NoMethodError)

          translations[locale.to_s]
                      ^^^^^^^^^^^^^
```

The above issue does not happen in `1.2.9`

Config
```ruby
Mobility.configure do
  plugins do
    backend :jsonb
    active_record

    reader
    writer

    cache

    dirty
    presence
  end
end
```

**Comment by shioyama** [comment]
This is well documented in the release notes. Mobility has been in alpha/rc for over a year because of this. This is not a bug.

**Comment by artemave** [comment]
In OP's defense, one wouldn't expect breaking changes with minor version bump.

I've been scratching my head facing the same issue, and it didn't occur to me to check the changelog, since there were no major version change.

**Comment by artemave** [comment]
I don't understand why this issue has been closed. The gem is clearly broken as it stands and there is no documentation as to how to make work. The only suggestion I've found buried in the pr comments was to disable "cache" plugin, but it didn't resolve the issue for me.

Back to 1.2.9 for the time being.
