### ISSUE TITLE
JSONB error using Sequel 4 and Hanami

### ISSUE THREAD

**Issue by jnylen** [shioyama/mobility#76]
RE: #75 
There are two different errors popping up as you try to add a new item in a model that has mobility loaded and pointed at the jsonb columns.

## Context

Gems:
hanami 1.0.0
sequel (4.49.0)
sequel-annotate (1.0.0)
sequel-rake (0.1.0)
sequel_pg (1.7.0)
sequel_polymorphic (0.3.1)
sequel_sluggable (0.0.6)

Columns are created with:
`jsonb :synopsis`

Except for title who has `null: false`

Model:
```
  translates :title, type: :string
  translates :synopsis, type: :text
```

## Expected Behavior
Well, it should create the item.

## Actual Behavior
When creating an item with a null column which is jsonb and mobility pointed at:
`Sequel::Error: The AND operator requires at least 1 argument`

When specifying data for both jsonb columns (title and synopsis):
```
2.3.3 :004 > 
m.synopsis = "test"
 => "test" 
2.3.3 :005 > m.save
Sequel::DatabaseError: PG::DatatypeMismatch: ERROR:  column "synopsis" is of type jsonb but expression is of type boolean
LINE 1: ...gas" ("synopsis", "title", "created_at") VALUES (('en' = 'te...
                                                             ^
HINT:  You will need to rewrite or cast the expression.
```

This hits both translated columns it just seems to put the error out on the last one though.
If I comment out the translates one on synopsis it hits the title one.

## Possible Fix
Might be Sequel's fault.

**Comment by jnylen** [comment]
Changing to 4.46 on Sequel does not help.

**Comment by jnylen** [comment]
@shioyama,
If I add it manually using Sequel.pg_json it works fine.
So can't be Sequel then.

**Comment by shioyama** [comment]
It only happens with one of the two columns? That's very strange.

**Comment by jnylen** [comment]
No, both, but the error will always say its the last one.

**Comment by shioyama** [comment]
It's really hard to debug given what you have there. There's a suite of specs for Sequel that pass so I don't really know what would be causing this.

Did you include the the jsonb extension with: `DB.extension :pg_json` ?

**Comment by shioyama** [comment]
Actually I think that's the issue: you need the pg_json extension. If I remove that from specs, I get the same errors. Should make a note of that in the readme + docs.

**Comment by shioyama** [comment]
More info here: http://sequel.jeremyevans.net/rdoc-plugins/files/lib/sequel/extensions/pg_json_rb.html

**Comment by jnylen** [comment]
Yeah I did,
Here is the full config:
```
require 'sequel'
Sequel::Model.plugin :timestamps
Sequel.extension :migration, :pg_array, :pg_json, :pg_json_ops, :pagination,
                 :pg_array_ops
DB = Sequel.connect(
  ENV["DATABASE_URL"],
  max_connections: 10,
  logger: Logger.new("log/sequel.log")
)
```

**Comment by shioyama** [comment]
No you need to include it with `DB.extension :pg_json` on your database.

**Comment by jnylen** [comment]
Damn. Thought they did the same thing.

Works now, thanks!

**Comment by shioyama** [comment]
Yeah, it's pretty confusing isn't it? A `Sequel` extension and a `DB` extension are not the same. I'll make a note in the docs.

Thanks for the feedback on Sequel! All issues so far have been about AR. Helps a lot.

**Comment by shioyama** [comment]
Also, a note: you don't need the `type:` options on `translates` for the Jsonb backend, those are just for the default KeyValue backend (to specify which table to use for storing translations). Jsonb will just ignore them but you don't need them.

**Comment by jnylen** [comment]
Apparently Sequel.extension isn't database specific while DB.extension is.

And also, thanks about the type thing. I'll remove them.
