### ISSUE TITLE
Error with initialization

### ISSUE THREAD

**Issue by pwim** [shioyama/mobility#82]
There appears to be a bug on line 257.

https://github.com/shioyama/mobility/blob/07a686309f32da425e3f3e876ec50f16cc3857a1/lib/mobility.rb#L248-L257

Rails was crashing when autoloading a model on `@mobility.dup`, as `@mobility` was nil. Because this is a loading issue, I don't think it is easy to reproduce. I'm guessing you mean `mobility.dup`, which appears to resolve the issue for me.

**Comment by shioyama** [comment]
Wow nice catch, yes that should be `mobility`. Could you make a PR? Don't need a test for it, as you said it would be very hard to test anyway. I guess in most cases load order doesn't trigger this issue, as long as `mobility` is called before it's inherited this won't happen.
