### ISSUE TITLE
locale_accessors & fallbacks

### ISSUE THREAD

**Issue by pwim** [shioyama/mobility#85]
When using locale_accessors, the locale specific accessors also use the fallbacks. e.g.,

``` ruby
Event.new(title_en: "foo").title_ja 
#=> "foo" instead of nil
```

I'm using the locale accessors to generate a form that provides the ability to edit an events title in Japanese and English (in two different form fields). With globalize, the locale specific accessors would return nil. This made it obvious which fields have not been translated. It also meant translations only got written when the user entered them. With mobility's current behaviour, if a user edits an event with an untranslated title and then saves it, the untranslated title will become the original title.

**Comment by shioyama** [comment]
https://github.com/shioyama/mobility/wiki/Using-Mobility-with-Forms

**Comment by shioyama** [comment]
I guess your point is slightly different, i.e. that fallbacks should be disabled for locale accessors.

**Comment by shioyama** [comment]
I thought about it and you're right of course, locale accessors should not fallback by default. See #86, which I think should do it.
